// Auto-generated by @skillship/sdk-plugin-auth. Do not edit by hand.
import { AuthError, ConfigError } from "./errors.js";

// Narrow ambient so resolveAuthFromEnv compiles without @types/node — the
// emitted package ships zero dependencies and a DOM-only lib. At runtime this is
// the real Node `process`; in non-Node hosts env simply resolves to undefined.
declare const process: { env: Record<string, string | undefined> };
export type AuthConfig =
  | {
      kind: "oauth2";
      clientId: string;
      clientSecret: string;
      tokenUrl?: string;
      scopes?: string[];
    }
  | { kind: "tokenProvider"; getToken: () => Promise<string> };

export function resolveAuthFromEnv(): AuthConfig | null {
  const env = process.env;
  if (env.AGENTMIN_CLIENT_ID && env.AGENTMIN_CLIENT_SECRET) {
    const tokenUrl =
      env.AGENTMIN_TOKEN_URL ?? "https://api.agentmin.test/oauth/token";
    return {
      kind: "oauth2",
      clientId: env.AGENTMIN_CLIENT_ID,
      clientSecret: env.AGENTMIN_CLIENT_SECRET,
      tokenUrl,
    };
  }
  return null;
}

export const REQUIRED_ENV_VARS: readonly string[] = [
  "AGENTMIN_CLIENT_ID",
  "AGENTMIN_CLIENT_SECRET",
];

export class AuthManager {
  private readonly auth: AuthConfig;
  private readonly fetchImpl: typeof fetch;
  private cachedToken: { token: string; expiresAt: number } | null = null;
  private inflight: Promise<string> | null = null;

  constructor(auth: AuthConfig, fetchImpl: typeof fetch) {
    this.auth = auth;
    this.fetchImpl = fetchImpl;
  }

  async applyAuth(
    headers: Record<string, string>,
    searchParams: URLSearchParams,
  ): Promise<void> {
    const auth = this.auth;
    if (auth.kind === "oauth2") {
      const token = await this.getOauth2Token();
      headers["Authorization"] = `Bearer ${token}`;
      return;
    }
    if (auth.kind === "tokenProvider") {
      const token = await auth.getToken();
      headers["Authorization"] = `Bearer ${token}`;
    }
  }

  onUnauthorized(): boolean {
    if (this.auth.kind === "oauth2" || this.auth.kind === "tokenProvider") {
      this.invalidate();
      return true;
    }
    return false;
  }

  invalidate(): void {
    this.cachedToken = null;
    this.inflight = null;
  }

  private getOauth2Token(): Promise<string> {
    const now = Date.now();
    if (this.cachedToken && this.cachedToken.expiresAt > now) {
      return Promise.resolve(this.cachedToken.token);
    }
    if (this.inflight) return this.inflight;
    const inflight = this.fetchOauth2Token(now).finally(() => {
      if (this.inflight === inflight) this.inflight = null;
    });
    this.inflight = inflight;
    return inflight;
  }

  private async fetchOauth2Token(now: number): Promise<string> {
    if (this.auth.kind !== "oauth2")
      throw new ConfigError("auth kind mismatch");
    const url = this.auth.tokenUrl ?? "https://api.agentmin.test/oauth/token";
    if (!url)
      throw new ConfigError(
        "tokenUrl is required for oauth2 but was not provided",
      );
    const { clientId, clientSecret } = this.auth;
    const credentials = btoa(`${clientId}:${clientSecret}`);
    const body = new URLSearchParams();
    body.set("grant_type", "client_credentials");
    const scopeStr = this.auth.scopes?.join(" ") ?? "";
    if (scopeStr) {
      body.set("scope", scopeStr);
    }
    const res = await this.fetchImpl(url, {
      method: "POST",
      headers: {
        Authorization: `Basic ${credentials}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: body.toString(),
    });
    if (!res.ok) {
      throw new AuthError(`token endpoint returned ${res.status}: ${url}`);
    }
    const json = (await res.json()) as Record<string, unknown>;
    const token = json["access_token"];
    if (typeof token !== "string")
      throw new AuthError("malformed token response");
    const expires_in =
      typeof json["expires_in"] === "number" ? json["expires_in"] : undefined;
    this.cachedToken = {
      token,
      expiresAt: now + (expires_in ?? 300) * 1000 - 60 * 1000,
    };
    return token;
  }
}
