// Auto-generated by @skillship/sdk-plugin-mcp-catalog. Do not edit by hand.

export interface CatalogParam {
  readonly name: string;
  readonly in: "path" | "query" | "body";
  readonly type: string;
  readonly required: boolean;
}

export interface CatalogEntry {
  readonly id: string;
  readonly accessor: readonly [string, string];
  readonly httpMethod: string;
  readonly path: string;
  readonly summary: string;
  readonly description: string;
  readonly params: readonly CatalogParam[];
  readonly annotations: {
    readonly destructive: boolean;
    readonly readOnly: boolean;
    readonly idempotent: boolean;
  };
  readonly paginated: boolean;
}

export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "events_list",
    accessor: ["events", "list"] as const,
    httpMethod: "GET",
    path: "/events",
    summary: "Returns events for the account.",
    description:
      "Returns events for the account. Paginated using cursor and per_page. Supports filtering by type.",
    params: [
      {
        name: "cursor",
        in: "query",
        type: "string",
        required: false,
      },
      {
        name: "per_page",
        in: "query",
        type: "integer",
        required: false,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: true,
      idempotent: true,
    },
    paginated: true,
  },
  {
    id: "items_create",
    accessor: ["items", "create"] as const,
    httpMethod: "POST",
    path: "/items",
    summary: "Create an item",
    description: "",
    params: [
      {
        name: "body",
        in: "body",
        type: "object",
        required: true,
      },
    ],
    annotations: {
      destructive: true,
      readOnly: false,
      idempotent: false,
    },
    paginated: false,
  },
  {
    id: "items_list",
    accessor: ["items", "list"] as const,
    httpMethod: "GET",
    path: "/items",
    summary: "List items (cursor-paginated)",
    description: "Returns a cursor-paginated page of items.",
    params: [
      {
        name: "cursor",
        in: "query",
        type: "string",
        required: false,
      },
      {
        name: "limit",
        in: "query",
        type: "integer",
        required: false,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: true,
      idempotent: true,
    },
    paginated: true,
  },
  {
    id: "logs_list",
    accessor: ["logs", "list"] as const,
    httpMethod: "GET",
    path: "/logs",
    summary: "List logs (offset-paginated)",
    description: "Returns an offset-paginated page of log lines.",
    params: [
      {
        name: "limit",
        in: "query",
        type: "integer",
        required: false,
      },
      {
        name: "offset",
        in: "query",
        type: "integer",
        required: false,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: true,
      idempotent: true,
    },
    paginated: true,
  },
  {
    id: "oauth_token",
    accessor: ["oauth", "token"] as const,
    httpMethod: "POST",
    path: "/oauth/token",
    summary: "Issue an OAuth2 access token",
    description: "Client-credentials token endpoint. Intentionally authless.",
    params: [],
    annotations: {
      destructive: false,
      readOnly: false,
      idempotent: false,
    },
    paginated: false,
  },
];
