// Auto-generated by @skillship/sdk-plugin-mcp-server. Do not edit by hand.
import { CATALOG, type CatalogEntry } from "./mcp-catalog.js";
import {
  makeProtocolHandler,
  runStdioServer,
  type ToolDef,
  type ToolResult,
  type JsonRpcRequest,
  type JsonRpcResponse,
} from "./mcp-protocol.js";
import { Client } from "./runtime.js";
import { attachResources } from "./resources.js";

// Narrow ambient so this module compiles without @types/node — the emitted
// package ships zero dependencies and a DOM-only lib. The protocol module owns
// the wide transport shape; this module only reads env. The declaration is
// module-scoped, so the two ambients never collide.
declare const process: { env: Record<string, string | undefined> };

// deps.env governs base-URL resolution and the destructive override only; AUTH
// always reads the real process.env via the SDK's resolveAuthFromEnv, so tests
// can swap base-URL/override env without having to inject credentials here.
export interface GatewayDeps {
  readonly fetchImpl?: typeof fetch;
  readonly env?: Record<string, string | undefined>;
}

const MAX_RESULT_CHARS = 50000;

function tokenize(s: string): readonly string[] {
  return s
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length > 0);
}

// Whole-token weighted score: id-tokens 4, summary 3, path 2, description 1.
function scoreEntry(
  entry: CatalogEntry,
  queryTokens: readonly string[],
): number {
  const idTokens = new Set(entry.id.split("_").filter((t) => t.length > 0));
  const summaryTokens = new Set(tokenize(entry.summary));
  const pathTokens = new Set(tokenize(entry.path));
  const descTokens = new Set(tokenize(entry.description));
  let score = 0;
  for (const q of queryTokens) {
    if (idTokens.has(q)) score += 4;
    if (summaryTokens.has(q)) score += 3;
    if (pathTokens.has(q)) score += 2;
    if (descTokens.has(q)) score += 1;
  }
  return score;
}

// Closest ids to a bad id, by scoring CATALOG ids against the bad id's tokens.
// Uses tokenize() so Items-Delete/items-delete find their neighbor via case-fold + non-alphanum split.
function closestIds(badId: string, n: number): readonly string[] {
  const tokens = tokenize(badId);
  const scored = CATALOG.map((e) => {
    const ids = new Set(tokenize(e.id));
    let s = 0;
    for (const t of tokens) if (ids.has(t)) s += 1;
    return { id: e.id, s };
  });
  scored.sort((a, b) => b.s - a.s || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return scored.slice(0, n).map((x) => x.id);
}

function findEntry(id: string): CatalogEntry | undefined {
  return CATALOG.find((e) => e.id === id);
}

function text(t: string, isError = false): ToolResult {
  return { content: [{ type: "text", text: t }], isError };
}

const TOOLS: readonly ToolDef[] = [
  {
    name: "search_operations",
    description:
      "Search this API's operations by keyword. Use this FIRST to discover the operation id you need, then call describe_operation or invoke_operation. Matches operation ids, summaries, paths, and descriptions.",
    inputSchema: {
      type: "object",
      properties: {
        query: { type: "string", description: "Keywords to match." },
        limit: {
          type: "integer",
          minimum: 1,
          maximum: 25,
          description: "Max hits (default 10).",
        },
      },
      required: ["query"],
    },
  },
  {
    name: "describe_operation",
    description:
      "Show the full signature of one operation: HTTP method and path, summary, every parameter (name, location, type, required), auth requirements, and pagination/confirmation notes. Use this before invoke_operation to learn exactly which args to pass.",
    inputSchema: {
      type: "object",
      properties: {
        id: {
          type: "string",
          description: "Operation id from search_operations.",
        },
      },
      required: ["id"],
    },
  },
  {
    name: "invoke_operation",
    description:
      "Execute one operation against the live API. Pass the operation id and an args object keyed by parameter name. Destructive operations require confirm: true. Returns the JSON response body.",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Operation id." },
        args: { type: "object", description: "Args keyed by parameter name." },
        confirm: {
          type: "boolean",
          description: "Required (true) for destructive operations.",
        },
      },
      required: ["id"],
    },
  },
];

function runSearch(args: Record<string, unknown>): ToolResult {
  const query = typeof args["query"] === "string" ? args["query"] : "";
  const rawLimit = typeof args["limit"] === "number" ? args["limit"] : 10;
  const limit = Math.max(1, Math.min(25, Math.floor(rawLimit)));
  const queryTokens = tokenize(query);
  const scored = CATALOG.map((entry) => ({
    entry,
    score: scoreEntry(entry, queryTokens),
  })).filter((x) => x.score > 0);
  // Stable sort: score desc, then id asc.
  scored.sort(
    (a, b) =>
      b.score - a.score ||
      (a.entry.id < b.entry.id ? -1 : a.entry.id > b.entry.id ? 1 : 0),
  );
  if (scored.length === 0) {
    const examples = CATALOG.slice(0, 5)
      .map((e) => e.id)
      .join(", ");
    return text("No matches. Example operations: " + examples);
  }
  const lines = scored.slice(0, limit).map((x) => {
    const e = x.entry;
    const suffix = e.annotations.destructive ? " [destructive]" : "";
    return (
      e.id + " — " + e.httpMethod + " " + e.path + " — " + e.summary + suffix
    );
  });
  return text(lines.join("\n"));
}

function runDescribe(args: Record<string, unknown>): ToolResult {
  const id = typeof args["id"] === "string" ? args["id"] : "";
  const entry = findEntry(id);
  if (entry === undefined) {
    const suggestions = closestIds(id, 3).join(", ");
    return text(
      "Unknown operation '" + id + "'. Closest: " + suggestions,
      true,
    );
  }
  const lines: string[] = [];
  lines.push(entry.id + " — " + entry.httpMethod + " " + entry.path);
  if (entry.summary) lines.push(entry.summary);
  if (entry.description) lines.push(entry.description);
  lines.push("");
  lines.push("Parameters:");
  if (entry.params.length === 0) {
    lines.push("  (none)");
  } else {
    for (const p of entry.params) {
      const req = p.required ? "required" : "optional";
      lines.push("  " + p.name + " — " + p.in + " — " + p.type + " — " + req);
    }
  }
  const a = entry.annotations;
  lines.push(
    "Annotations: destructive=" +
      a.destructive +
      ", readOnly=" +
      a.readOnly +
      ", idempotent=" +
      a.idempotent,
  );
  if (entry.paginated) {
    lines.push(
      "Pagination: accepts cursor/offset params; the SDK exposes a " +
        entry.accessor[1] +
        "Pages helper.",
    );
  }
  lines.push("Auth: set AGENTMIN_CLIENT_ID, AGENTMIN_CLIENT_SECRET.");
  lines.push(
    "Base URL: https://api.agentmin.test/v1 (override with AGENTMIN_BASE_URL)",
  );
  if (a.destructive) {
    lines.push("Destructive: invoke_operation requires confirm: true.");
  }
  return text(lines.join("\n"));
}

type Gateway = ReturnType<typeof attachResources>;

function resolveBaseUrl(
  env: Record<string, string | undefined>,
): string | null {
  return env["AGENTMIN_BASE_URL"] ?? "https://api.agentmin.test/v1";
}

function routeArgs(
  entry: CatalogEntry,
  args: Record<string, unknown>,
):
  | { ok: true; opts: Record<string, unknown> }
  | { ok: false; message: string } {
  const valid = new Set(entry.params.map((p) => p.name));
  const unknown = Object.keys(args).filter((k) => !valid.has(k));
  if (unknown.length > 0) {
    const names = entry.params.map((p) => p.name).join(", ") || "(none)";
    return {
      ok: false,
      message:
        "unknown_args: " + unknown.join(", ") + ". Valid params: " + names,
    };
  }
  const missing = entry.params.filter((p) => p.required && !(p.name in args));
  if (missing.length > 0) {
    const names = missing.map((p) => p.name + " (" + p.in + ")").join(", ");
    return {
      ok: false,
      message: "missing_args: " + entry.id + " requires: " + names,
    };
  }
  const pathParams: Record<string, unknown> = {};
  const query: Record<string, unknown> = {};
  let body: unknown = undefined;
  for (const p of entry.params) {
    if (!(p.name in args)) continue;
    if (p.in === "path") pathParams[p.name] = args[p.name];
    else if (p.in === "query") query[p.name] = args[p.name];
    else body = args[p.name];
  }
  const opts: Record<string, unknown> = {};
  if (Object.keys(pathParams).length > 0) opts["pathParams"] = pathParams;
  if (Object.keys(query).length > 0) opts["query"] = query;
  if (body !== undefined) opts["body"] = body;
  return { ok: true, opts };
}

async function runInvoke(
  args: Record<string, unknown>,
  env: Record<string, string | undefined>,
  getClient: () => Gateway,
): Promise<ToolResult> {
  const id = typeof args["id"] === "string" ? args["id"] : "";
  const entry = findEntry(id);
  if (entry === undefined) {
    return text(
      "Unknown operation '" +
        id +
        "'. Closest: " +
        closestIds(id, 3).join(", "),
      true,
    );
  }
  const callArgs =
    typeof args["args"] === "object" &&
    args["args"] !== null &&
    !Array.isArray(args["args"])
      ? (args["args"] as Record<string, unknown>)
      : {};
  const confirm = args["confirm"] === true;
  if (
    entry.annotations.destructive &&
    !confirm &&
    env["AGENTMIN_MCP_ALLOW_DESTRUCTIVE"] !== "1"
  ) {
    return text(
      "destructive_confirmation_required: " +
        entry.id +
        " is destructive (" +
        entry.httpMethod +
        " " +
        entry.path +
        "). Re-invoke with confirm: true after user approval.",
      true,
    );
  }
  const routed = routeArgs(entry, callArgs);
  if (!routed.ok) return text(routed.message, true);
  const baseUrl = resolveBaseUrl(env);
  if (baseUrl === null) {
    return text("base_url_not_set: set AGENTMIN_BASE_URL.", true);
  }
  try {
    const client = getClient();
    // accessor[0] is a ResourceTree group key, but Gateway is Client &
    // ResourceTree, so indexing by keyof Gateway yields a union that also
    // includes Client's own members (request method, baseUrl, …) whose shapes
    // do not overlap the resource record. Go through unknown — the catalog
    // guarantees accessor points at a real resource method.
    const ns = client[entry.accessor[0] as keyof Gateway] as unknown as Record<
      string,
      (opts?: Record<string, unknown>) => Promise<unknown>
    >;
    const result = await ns[entry.accessor[1]](routed.opts);
    let out: string;
    if (result instanceof Response) {
      const raw = await result.text();
      try {
        out = JSON.stringify(JSON.parse(raw) as unknown, null, 2);
      } catch {
        out = raw;
      }
    } else {
      out = JSON.stringify(result, null, 2);
    }
    if (out.length > MAX_RESULT_CHARS) {
      out =
        out.slice(0, MAX_RESULT_CHARS) +
        "\n…[truncated — response exceeded 50,000 characters]";
    }
    return text(out);
  } catch (err: unknown) {
    const name = err instanceof Error ? err.name : "Error";
    const message = err instanceof Error ? err.message : String(err);
    return text(name + ": " + message, true);
  }
}

export function createGateway(
  deps?: GatewayDeps,
): (msg: JsonRpcRequest) => Promise<JsonRpcResponse | null> {
  const env = deps?.env ?? process.env;
  let cached: Gateway | null = null;
  const getClient = (): Gateway => {
    if (cached !== null) return cached;
    const baseUrl = resolveBaseUrl(env);
    if (baseUrl === null) throw new Error("base_url_not_set"); // unreachable: runInvoke checks first
    cached = attachResources(
      new Client({
        baseUrl,
        ...(deps?.fetchImpl ? { fetch: deps.fetchImpl } : {}),
      }),
    );
    return cached;
  };
  const callTool = (
    name: string,
    args: Record<string, unknown>,
  ): Promise<ToolResult> => {
    if (name === "search_operations") return Promise.resolve(runSearch(args));
    if (name === "describe_operation")
      return Promise.resolve(runDescribe(args));
    if (name === "invoke_operation") return runInvoke(args, env, getClient);
    return Promise.resolve(text("unknown tool: " + name, true)); // unreachable: protocol layer pre-filters unknown tools
  };
  return makeProtocolHandler({
    serverName: "agentmin-mcp",
    serverVersion: "0.1.0",
    tools: TOOLS,
    callTool,
  });
}

export function main(): void {
  runStdioServer(createGateway());
}
