// Auto-generated by @skillship/sdk-plugin-pagination. Do not edit by hand.

interface PaginatePlan {
  style: "cursor" | "offset" | "page";
  requestParam: string;
  pageSizeParam: string | null;
  itemsField: string;
  nextField: string | null;
  opId: string;
}

async function* paginateCursor<Item>(
  fetchPage: (pageArgs: Record<string, unknown>) => Promise<unknown>,
  plan: PaginatePlan,
): AsyncGenerator<Item> {
  let cursor: unknown = undefined;
  for (;;) {
    const pageArgs: Record<string, unknown> =
      cursor != null ? { [plan.requestParam]: cursor } : {};
    const body = await fetchPage(pageArgs);
    if (typeof body !== "object" || body === null) return;
    const record = body as Record<string, unknown>;
    const items = record[plan.itemsField];
    if (!Array.isArray(items)) {
      throw new TypeError(
        `paginate(${plan.opId}): response body missing array field "${plan.itemsField}"`,
      );
    }
    if (items.length === 0) return;
    for (const item of items) yield item as Item;
    const nextField = plan.nextField;
    if (nextField === null) return;
    const next = record[nextField];
    if (next == null || next === "") return;
    if (next === cursor) return;
    cursor = next;
  }
}

async function* paginateOffsetOrPage<Item>(
  fetchPage: (pageArgs: Record<string, unknown>) => Promise<unknown>,
  plan: PaginatePlan,
  requestedPageSize: number | undefined,
): AsyncGenerator<Item> {
  let counter = plan.style === "page" ? 1 : 0;
  for (;;) {
    const pageArgs: Record<string, unknown> = { [plan.requestParam]: counter };
    const body = await fetchPage(pageArgs);
    if (typeof body !== "object" || body === null) return;
    const record = body as Record<string, unknown>;
    const items = record[plan.itemsField];
    if (!Array.isArray(items)) {
      throw new TypeError(
        `paginate(${plan.opId}): response body missing array field "${plan.itemsField}"`,
      );
    }
    if (items.length === 0) return;
    for (const item of items) yield item as Item;
    if (requestedPageSize !== undefined && items.length < requestedPageSize)
      return;
    counter += plan.style === "page" ? 1 : items.length;
  }
}

export async function* paginate<Item>(
  fetchPage: (pageArgs: Record<string, unknown>) => Promise<unknown>,
  plan: PaginatePlan,
  requestedPageSize?: number,
): AsyncGenerator<Item> {
  if (plan.style === "cursor") {
    yield* paginateCursor<Item>(fetchPage, plan);
  } else {
    yield* paginateOffsetOrPage<Item>(fetchPage, plan, requestedPageSize);
  }
}
