// Auto-generated by @skillship/sdk-plugin-resource-tree. Do not edit by hand.
import { Client } from "./runtime.js";
import { paginate } from "./pagination.js";

export interface ResourceTree {
  readonly events: {
    list: (opts?: RequestOpts) => Promise<Response>;
    listPages: (opts?: RequestOpts) => AsyncGenerator<unknown>;
  };
  readonly items: {
    list: (opts?: RequestOpts) => Promise<Response>;
    listPages: (opts?: RequestOpts) => AsyncGenerator<unknown>;
    create: (opts?: RequestOpts) => Promise<Response>;
  };
  readonly logs: {
    list: (opts?: RequestOpts) => Promise<Response>;
    listPages: (opts?: RequestOpts) => AsyncGenerator<unknown>;
  };
  readonly oauth: { token: (opts?: RequestOpts) => Promise<Response> };
}

interface RequestOpts {
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
  body?: unknown;
  pathParams?: Record<string, string | number>;
}

export function attachResources(client: Client): Client & ResourceTree {
  return Object.assign(client, {
    events: {
      list: (opts?: RequestOpts) =>
        client.request({
          method: "GET",
          path: "/events",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
      listPages: (opts?: RequestOpts): AsyncGenerator<unknown> =>
        paginate<unknown>(
          (pageArgs) =>
            client
              .request({
                method: "GET",
                path: "/events",
                pathParams: opts?.pathParams,
                query: {
                  ...opts?.query,
                  ...(pageArgs as Record<
                    string,
                    string | number | boolean | undefined
                  >),
                },
                headers: opts?.headers,
                body: opts?.body,
              })
              .then((r) => r.json() as Promise<unknown>),
          {
            style: "cursor",
            requestParam: "cursor",
            pageSizeParam: "per_page",
            itemsField: "data.results",
            nextField: "data.next_cursor",
            opId: "op_e64e8ca3293f7d36",
          },
          typeof opts?.query?.["per_page"] === "number"
            ? (opts.query["per_page"] as number)
            : undefined,
        ),
    },
    items: {
      list: (opts?: RequestOpts) =>
        client.request({
          method: "GET",
          path: "/items",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
      listPages: (opts?: RequestOpts): AsyncGenerator<unknown> =>
        paginate<unknown>(
          (pageArgs) =>
            client
              .request({
                method: "GET",
                path: "/items",
                pathParams: opts?.pathParams,
                query: {
                  ...opts?.query,
                  ...(pageArgs as Record<
                    string,
                    string | number | boolean | undefined
                  >),
                },
                headers: opts?.headers,
                body: opts?.body,
              })
              .then((r) => r.json() as Promise<unknown>),
          {
            style: "cursor",
            requestParam: "cursor",
            pageSizeParam: "limit",
            itemsField: "data",
            nextField: "next_cursor",
            opId: "op_15af9ffbbece6c20",
          },
          typeof opts?.query?.["limit"] === "number"
            ? (opts.query["limit"] as number)
            : undefined,
        ),
      create: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/items",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
    logs: {
      list: (opts?: RequestOpts) =>
        client.request({
          method: "GET",
          path: "/logs",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
      listPages: (opts?: RequestOpts): AsyncGenerator<unknown> =>
        paginate<unknown>(
          (pageArgs) =>
            client
              .request({
                method: "GET",
                path: "/logs",
                pathParams: opts?.pathParams,
                query: {
                  ...opts?.query,
                  ...(pageArgs as Record<
                    string,
                    string | number | boolean | undefined
                  >),
                },
                headers: opts?.headers,
                body: opts?.body,
              })
              .then((r) => r.json() as Promise<unknown>),
          {
            style: "offset",
            requestParam: "offset",
            pageSizeParam: "limit",
            itemsField: "data",
            nextField: null,
            opId: "op_1ca02acda58364c6",
          },
          typeof opts?.query?.["limit"] === "number"
            ? (opts.query["limit"] as number)
            : undefined,
        ),
    },
    oauth: {
      token: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/oauth/token",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
  });
}
