// Auto-generated by @skillship/sdk-plugin-runtime. Do not edit by hand.
import {
  throwForResponse,
  TimeoutError,
  UnauthorizedError,
  ConfigError,
} from "./errors.js";
import {
  AuthManager,
  resolveAuthFromEnv,
  REQUIRED_ENV_VARS,
  type AuthConfig,
} from "./auth.js";

export type { AuthConfig } from "./auth.js";

const MAX_RETRIES = 2;
const RETRYABLE_STATUS: readonly number[] = [408, 409, 429, 500, 502, 503, 504];
const BASE_DELAY_MS = 500;
const MAX_DELAY_MS = 30000;
const HONOR_RETRY_AFTER = true;
const IDEMPOTENT_METHODS: readonly string[] = [
  "GET",
  "HEAD",
  "PUT",
  "DELETE",
  "OPTIONS",
];
// Non-idempotent methods (POST/PATCH) retry ONLY these statuses, never network errors or timeouts.
const NON_IDEMPOTENT_RETRYABLE: readonly number[] = [408, 429];

function defaultSleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export interface ClientOptions {
  baseUrl: string;
  auth?: AuthConfig;
  defaultHeaders?: Record<string, string>;
  fetch?: typeof fetch;
  timeout?: number;
  sleep?: (ms: number) => Promise<void>;
  onRequest?: (req: Request) => Request | Promise<Request>;
  onResponse?: (res: Response) => Response | Promise<Response>;
}

export class Client {
  readonly baseUrl: string;
  readonly defaultHeaders: Record<string, string>;
  readonly fetchImpl: typeof fetch;
  readonly timeout: number | undefined;
  readonly sleep: (ms: number) => Promise<void>;
  readonly onRequest:
    | ((req: Request) => Request | Promise<Request>)
    | undefined;
  readonly onResponse:
    | ((res: Response) => Response | Promise<Response>)
    | undefined;
  private readonly authManager: AuthManager;

  constructor(opts: ClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "") + "/";
    this.defaultHeaders = opts.defaultHeaders ?? {};
    this.fetchImpl = opts.fetch ?? globalThis.fetch;
    this.timeout = opts.timeout;
    this.sleep = opts.sleep ?? defaultSleep;
    this.onRequest = opts.onRequest;
    this.onResponse = opts.onResponse;
    // Resolve auth: explicit option > environment > ConfigError listing env vars.
    const auth = opts.auth ?? resolveAuthFromEnv();
    if (auth === null) {
      const names = REQUIRED_ENV_VARS.join(", ");
      throw new ConfigError(
        `no auth configured: pass the 'auth' option or set ${names}`,
      );
    }
    this.authManager = new AuthManager(auth, this.fetchImpl);
  }

  async request(input: {
    path: string;
    method: string;
    pathParams?: Record<string, string | number>;
    query?: Record<string, string | number | boolean | undefined>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<Response> {
    return this.executeWithAuthRefresh(input);
  }

  private buildTarget(input: {
    path: string;
    pathParams?: Record<string, string | number>;
    query?: Record<string, string | number | boolean | undefined>;
    headers?: Record<string, string>;
  }): { url: URL; headers: Record<string, string> } {
    let resolvedPath = input.path;
    if (input.pathParams) {
      for (const [k, v] of Object.entries(input.pathParams)) {
        resolvedPath = resolvedPath.replaceAll(
          `{${k}}`,
          encodeURIComponent(String(v)),
        );
      }
    }
    const relPath = resolvedPath.startsWith("/")
      ? resolvedPath.slice(1)
      : resolvedPath;
    const url = new URL(relPath, this.baseUrl);
    if (input.query) {
      for (const [k, v] of Object.entries(input.query)) {
        if (v !== undefined) url.searchParams.append(k, String(v));
      }
    }
    const headers: Record<string, string> = {
      ...this.defaultHeaders,
      ...(input.headers ?? {}),
    };
    return { url, headers };
  }

  private async executeWithAuthRefresh(input: {
    path: string;
    method: string;
    pathParams?: Record<string, string | number>;
    query?: Record<string, string | number | boolean | undefined>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<Response> {
    let refreshed = false;
    for (;;) {
      const { url, headers } = this.buildTarget(input);
      await this.authManager.applyAuth(headers, url.searchParams);
      const { res, attempts } = await this.runRetryLoop(
        input.method,
        url,
        headers,
        input.body,
      );
      if (
        res.status === 401 &&
        !refreshed &&
        this.authManager.onUnauthorized()
      ) {
        refreshed = true;
        continue;
      }
      return this.finalize(res, attempts);
    }
  }

  private async finalize(res: Response, attempts: number): Promise<Response> {
    let out = res;
    if (this.onResponse) out = await this.onResponse(out);
    if (!out.ok) {
      const requestId = out.headers.get("x-request-id");
      let body: unknown = null;
      try {
        body = await out.clone().json();
      } catch {
        try {
          body = await out.clone().text();
        } catch {
          /* ignore */
        }
      }
      // A 401 that reaches finalize survived the single auth-refresh retry.
      if (out.status === 401) {
        const msg401 =
          attempts > 1
            ? `API error 401 (after ${attempts} attempts)`
            : "API error 401";
        throw new UnauthorizedError({
          status: 401,
          requestId,
          body,
          code: null,
          message: msg401,
        });
      }
      const suffix = attempts > 1 ? ` (after ${attempts} attempts)` : "";
      throwForResponse({
        status: out.status,
        requestId,
        body,
        code: null,
        suffix,
      });
    }
    return out;
  }

  private async runRetryLoop(
    method: string,
    url: URL,
    headers: Record<string, string>,
    body: unknown,
  ): Promise<{ res: Response; attempts: number }> {
    const idempotent = IDEMPOTENT_METHODS.includes(method.toUpperCase());
    let lastError: unknown = null;
    let lastResponse: Response | null = null;
    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      const controller = new AbortController();
      const timeoutId =
        this.timeout !== undefined
          ? setTimeout(() => controller.abort(), this.timeout)
          : null;
      const init: RequestInit = { method, headers, signal: controller.signal };
      if (body !== undefined) {
        headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
        init.body = JSON.stringify(body);
      }
      let req = new Request(url.toString(), init);
      try {
        if (this.onRequest) req = await this.onRequest(req);
        const res = await this.fetchImpl(req);
        lastResponse = res;
        if (
          attempt < MAX_RETRIES &&
          this.shouldRetryStatus(res.status, idempotent)
        ) {
          await this.sleep(this.computeDelay(attempt, res));
          continue;
        }
        return { res, attempts: attempt + 1 };
      } catch (err) {
        const timedOut = controller.signal.aborted;
        lastError = timedOut
          ? new TimeoutError({
              status: 0,
              requestId: null,
              body: null,
              code: "timeout",
              message: `Request timed out after ${this.timeout}ms`,
            })
          : err;
        if (attempt < MAX_RETRIES && idempotent) {
          await this.sleep(this.computeDelay(attempt, null));
          continue;
        }
        throw this.exhausted(lastError, attempt + 1);
      } finally {
        if (timeoutId !== null) clearTimeout(timeoutId);
      }
    }
    if (lastResponse !== null)
      return { res: lastResponse, attempts: MAX_RETRIES + 1 };
    throw this.exhausted(lastError, MAX_RETRIES + 1);
  }

  private computeDelay(attempt: number, res: Response | null): number {
    const cap = Math.min(MAX_DELAY_MS, BASE_DELAY_MS * 2 ** attempt);
    const backoff = Math.random() * cap;
    if (HONOR_RETRY_AFTER && res !== null) {
      const ra = this.parseRetryAfter(res.headers.get("retry-after"));
      if (ra !== null) return Math.min(ra, MAX_DELAY_MS);
    }
    return backoff;
  }

  private parseRetryAfter(header: string | null): number | null {
    if (header === null) return null;
    const trimmed = header.trim();
    if (trimmed === "") return null;
    if (/^\d+$/.test(trimmed)) return Number(trimmed) * 1000;
    const dateMs = Date.parse(trimmed);
    if (!Number.isNaN(dateMs)) {
      const delta = dateMs - Date.now();
      return delta > 0 ? delta : 0;
    }
    // Unparseable Retry-After → caller falls back to the computed backoff.
    return null;
  }

  private shouldRetryStatus(status: number, idempotent: boolean): boolean {
    if (status === 401) return false;
    const set = idempotent ? RETRYABLE_STATUS : NON_IDEMPOTENT_RETRYABLE;
    return set.includes(status);
  }

  private exhausted(error: unknown, attempts: number): unknown {
    if (error instanceof Error) {
      if (attempts > 1)
        error.message = `${error.message} (after ${attempts} attempts)`;
      return error;
    }
    const suffix = attempts > 1 ? ` (after ${attempts} attempts)` : "";
    return new TimeoutError({
      status: 0,
      requestId: null,
      body: null,
      code: "exhausted",
      message: `request failed${suffix}`,
    });
  }
}
