// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import type {
  Op15Af9Ffbbece6C20Data,
  Op15Af9Ffbbece6C20Responses,
  Op1Ca02Acda58364C6Data,
  Op1Ca02Acda58364C6Responses,
  Op30E7D79D32E7C322Data,
  Op30E7D79D32E7C322Responses,
  Op4182B9B8145F98B7Data,
  Op4182B9B8145F98B7Responses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List items (cursor-paginated)
 *
 * Returns a cursor-paginated page of items.
 */
export const op15Af9Ffbbece6C20 = <ThrowOnError extends boolean = false>(
  options?: Options<Op15Af9Ffbbece6C20Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    Op15Af9Ffbbece6C20Responses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/items",
    ...options,
  });

/**
 * Create an item
 */
export const op30E7D79D32E7C322 = <ThrowOnError extends boolean = false>(
  options: Options<Op30E7D79D32E7C322Data, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Op30E7D79D32E7C322Responses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/items",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List logs (offset-paginated)
 *
 * Returns an offset-paginated page of log lines.
 */
export const op1Ca02Acda58364C6 = <ThrowOnError extends boolean = false>(
  options?: Options<Op1Ca02Acda58364C6Data, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    Op1Ca02Acda58364C6Responses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/logs",
    ...options,
  });

/**
 * Issue an OAuth2 access token
 *
 * Client-credentials token endpoint. Intentionally authless.
 */
export const op4182B9B8145F98B7 = <ThrowOnError extends boolean = false>(
  options?: Options<Op4182B9B8145F98B7Data, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    Op4182B9B8145F98B7Responses,
    unknown,
    ThrowOnError
  >({ url: "/oauth/token", ...options });
