// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type Op15Af9Ffbbece6C20Data = {
  body?: never;
  path?: never;
  query?: {
    cursor?: string;
    limit?: number;
  };
  url: "/items";
};

export type Op15Af9Ffbbece6C20Responses = {
  /**
   * 200
   */
  200: {
    data?: Array<{
      id?: string;
      name?: string;
    }>;
    next_cursor?: string;
  };
};

export type Op15Af9Ffbbece6C20Response =
  Op15Af9Ffbbece6C20Responses[keyof Op15Af9Ffbbece6C20Responses];

export type Op30E7D79D32E7C322Data = {
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/items";
};

export type Op30E7D79D32E7C322Responses = {
  /**
   * 201
   */
  201: {
    id?: string;
    name?: string;
  };
};

export type Op30E7D79D32E7C322Response =
  Op30E7D79D32E7C322Responses[keyof Op30E7D79D32E7C322Responses];

export type Op1Ca02Acda58364C6Data = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    offset?: number;
  };
  url: "/logs";
};

export type Op1Ca02Acda58364C6Responses = {
  /**
   * 200
   */
  200: {
    data?: Array<{
      message?: string;
    }>;
  };
};

export type Op1Ca02Acda58364C6Response =
  Op1Ca02Acda58364C6Responses[keyof Op1Ca02Acda58364C6Responses];

export type Op4182B9B8145F98B7Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/oauth/token";
};

export type Op4182B9B8145F98B7Responses = {
  /**
   * 200
   */
  200: {
    access_token?: string;
    token_type?: string;
    expires_in?: number;
  };
};

export type Op4182B9B8145F98B7Response =
  Op4182B9B8145F98B7Responses[keyof Op4182B9B8145F98B7Responses];
