# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawOauthClient, RawOauthClient
from .types.oauth_token_response import OauthTokenResponse


class OauthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOauthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOauthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOauthClient
        """
        return self._raw_client

    def token(self, *, request_options: typing.Optional[RequestOptions] = None) -> OauthTokenResponse:
        """
        Client-credentials token endpoint. Intentionally authless.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthTokenResponse
            200

        Examples
        --------
        from skillship_sdk import SkillshipApi

        client = SkillshipApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.oauth.token()
        """
        _response = self._raw_client.token(request_options=request_options)
        return _response.data


class AsyncOauthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOauthClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOauthClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOauthClient
        """
        return self._raw_client

    async def token(self, *, request_options: typing.Optional[RequestOptions] = None) -> OauthTokenResponse:
        """
        Client-credentials token endpoint. Intentionally authless.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OauthTokenResponse
            200

        Examples
        --------
        import asyncio

        from skillship_sdk import AsyncSkillshipApi

        client = AsyncSkillshipApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.oauth.token()


        asyncio.run(main())
        """
        _response = await self._raw_client.token(request_options=request_options)
        return _response.data
