# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawEventsClient, RawEventsClient
from .types.events_list_response import EventsListResponse


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventsListResponse:
        """
        Returns events for the account. Paginated using cursor and per_page. Supports filtering by type.

        Parameters
        ----------
        cursor : typing.Optional[str]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventsListResponse
            200

        Examples
        --------
        from skillship_sdk import SkillshipApi

        client = SkillshipApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )
        client.events.list()
        """
        _response = self._raw_client.list(cursor=cursor, per_page=per_page, request_options=request_options)
        return _response.data


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventsListResponse:
        """
        Returns events for the account. Paginated using cursor and per_page. Supports filtering by type.

        Parameters
        ----------
        cursor : typing.Optional[str]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventsListResponse
            200

        Examples
        --------
        import asyncio

        from skillship_sdk import AsyncSkillshipApi

        client = AsyncSkillshipApi(
            token="YOUR_TOKEN",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.events.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(cursor=cursor, per_page=per_page, request_options=request_options)
        return _response.data
