// src/sdk-plugins/auth.ts
// Emits the auth.ts module: AuthConfig union, resolveAuthFromEnv, AuthManager.
// OAuth2 client-credentials token fetch uses the injected fetchImpl (never
// globalThis.fetch). Token cache: { token, expiresAt } + single-flight Promise.

import type { AuthSchemeDescriptor } from "./runtime.js";

export function generateAuthModule(
  schemes: readonly AuthSchemeDescriptor[],
  envPrefix: string,
): string {
  const authUnion = buildAuthUnion(schemes);
  const resolveEnv = buildResolveAuthFromEnv(schemes, envPrefix);
  const authManager = buildAuthManager(schemes);
  return [
    buildHeader(),
    `export type AuthConfig = ${authUnion};`,
    "",
    resolveEnv,
    "",
    authManager,
  ].join("\n");
}

// ─── header ──────────────────────────────────────────────────────────────────

function buildHeader(): string {
  return `// Auto-generated by @skillship/sdk-plugin-auth. Do not edit by hand.
import { AuthError, ConfigError } from "./errors.js";`;
}

// ─── AuthConfig union ────────────────────────────────────────────────────────

function buildAuthUnion(schemes: readonly AuthSchemeDescriptor[]): string {
  const parts: string[] = [];
  const seen = new Set<string>();
  for (const s of schemes) {
    if (s.kind === "bearer" && !seen.has("bearer")) {
      seen.add("bearer");
      parts.push('{ kind: "bearer"; token: string }');
    } else if (s.kind === "apiKey" && !seen.has("apiKey")) {
      seen.add("apiKey");
      parts.push('{ kind: "apiKey"; value: string; in: "header" | "query"; name: string }');
    } else if (s.kind === "basic" && !seen.has("basic")) {
      seen.add("basic");
      parts.push('{ kind: "basic"; username: string; password: string }');
    } else if (s.kind === "oauth2ClientCredentials" && !seen.has("oauth2")) {
      seen.add("oauth2");
      parts.push(
        '{ kind: "oauth2"; clientId: string; clientSecret: string; tokenUrl?: string; scopes?: string[] }',
      );
    }
    // external: no union member
  }
  // tokenProvider is ALWAYS present
  parts.push('{ kind: "tokenProvider"; getToken: () => Promise<string> }');
  return parts.join(" | ");
}

// ─── resolveAuthFromEnv ──────────────────────────────────────────────────────

function buildResolveAuthFromEnv(
  schemes: readonly AuthSchemeDescriptor[],
  prefix: string,
): string {
  const branches = buildEnvBranches(schemes, prefix);
  return [
    "export function resolveAuthFromEnv(): AuthConfig | null {",
    "  const env = process.env;",
    ...branches,
    "  return null;",
    "}",
  ].join("\n");
}

function buildEnvBranches(
  schemes: readonly AuthSchemeDescriptor[],
  prefix: string,
): string[] {
  const lines: string[] = [];
  const seen = new Set<string>();
  for (const s of schemes) {
    if (s.kind === "bearer" && !seen.has("bearer")) {
      seen.add("bearer");
      lines.push(`  if (env.${prefix}_TOKEN) {`);
      lines.push(`    return { kind: "bearer", token: env.${prefix}_TOKEN };`);
      lines.push("  }");
    } else if (s.kind === "apiKey" && !seen.has("apiKey")) {
      seen.add("apiKey");
      lines.push(`  if (env.${prefix}_API_KEY) {`);
      lines.push(`    return { kind: "apiKey", value: env.${prefix}_API_KEY, in: "${s.in}", name: "${s.name}" };`);
      lines.push("  }");
    } else if (s.kind === "basic" && !seen.has("basic")) {
      seen.add("basic");
      lines.push(`  if (env.${prefix}_USERNAME && env.${prefix}_PASSWORD) {`);
      lines.push(`    return { kind: "basic", username: env.${prefix}_USERNAME, password: env.${prefix}_PASSWORD };`);
      lines.push("  }");
    } else if (s.kind === "oauth2ClientCredentials" && !seen.has("oauth2")) {
      seen.add("oauth2");
      lines.push(...buildOauth2EnvBranch(s, prefix));
    }
  }
  return lines;
}

function buildOauth2EnvBranch(
  s: Extract<AuthSchemeDescriptor, { kind: "oauth2ClientCredentials" }>,
  prefix: string,
): string[] {
  const defaultUrl = s.tokenUrl !== null ? `"${s.tokenUrl}"` : "undefined";
  return [
    `  if (env.${prefix}_CLIENT_ID && env.${prefix}_CLIENT_SECRET) {`,
    `    const tokenUrl = env.${prefix}_TOKEN_URL ?? ${defaultUrl};`,
    `    return { kind: "oauth2", clientId: env.${prefix}_CLIENT_ID, clientSecret: env.${prefix}_CLIENT_SECRET, tokenUrl };`,
    "  }",
  ];
}

// ─── AuthManager ─────────────────────────────────────────────────────────────

function buildAuthManager(schemes: readonly AuthSchemeDescriptor[]): string {
  const hasOauth2 = schemes.some((s) => s.kind === "oauth2ClientCredentials");
  const fields = buildManagerFields(hasOauth2);
  const applyAuth = buildApplyAuth(schemes, hasOauth2);
  const onUnauthorized = buildOnUnauthorized(hasOauth2);
  const tokenFetch = hasOauth2 ? buildFetchToken(schemes) : "";
  const invalidate = buildInvalidate(hasOauth2);
  return [
    "export class AuthManager {",
    "  private readonly auth: AuthConfig;",
    "  private readonly fetchImpl: typeof fetch;",
    ...fields,
    "",
    "  constructor(auth: AuthConfig, fetchImpl: typeof fetch) {",
    "    this.auth = auth;",
    "    this.fetchImpl = fetchImpl;",
    "  }",
    "",
    applyAuth,
    "",
    onUnauthorized,
    ...(invalidate ? ["", invalidate] : []),
    ...(tokenFetch ? ["", tokenFetch] : []),
    "}",
  ].join("\n");
}

function buildManagerFields(hasOauth2: boolean): string[] {
  if (!hasOauth2) return [];
  return [
    "  private cachedToken: { token: string; expiresAt: number } | null = null;",
    "  private inflight: Promise<string> | null = null;",
  ];
}

function buildApplyAuth(
  schemes: readonly AuthSchemeDescriptor[],
  _hasOauth2: boolean,
): string {
  const branches = buildApplyBranches(schemes);
  return [
    "  async applyAuth(headers: Record<string, string>, searchParams: URLSearchParams): Promise<void> {",
    "    const auth = this.auth;",
    ...branches,
    "  }",
  ].join("\n");
}

function buildApplyBranches(
  schemes: readonly AuthSchemeDescriptor[],
): string[] {
  const lines: string[] = [];
  const seen = new Set<string>();
  for (const s of schemes) {
    if (s.kind === "bearer" && !seen.has("bearer")) {
      seen.add("bearer");
      lines.push('    if (auth.kind === "bearer") {');
      lines.push('      headers["Authorization"] = `Bearer ${auth.token}`;');
      lines.push("      return;");
      lines.push("    }");
    } else if (s.kind === "apiKey" && !seen.has("apiKey")) {
      seen.add("apiKey");
      lines.push('    if (auth.kind === "apiKey") {');
      lines.push('      if (auth.in === "header") headers[auth.name] = auth.value;');
      lines.push('      else searchParams.append(auth.name, auth.value);');
      lines.push("      return;");
      lines.push("    }");
    } else if (s.kind === "basic" && !seen.has("basic")) {
      seen.add("basic");
      lines.push('    if (auth.kind === "basic") {');
      lines.push("      const encoded = btoa(`${auth.username}:${auth.password}`);");
      lines.push('      headers["Authorization"] = `Basic ${encoded}`;');
      lines.push("      return;");
      lines.push("    }");
    } else if (s.kind === "oauth2ClientCredentials" && !seen.has("oauth2")) {
      seen.add("oauth2");
      lines.push('    if (auth.kind === "oauth2") {');
      lines.push("      const token = await this.getOauth2Token();");
      lines.push('      headers["Authorization"] = `Bearer ${token}`;');
      lines.push("      return;");
      lines.push("    }");
    }
  }
  // tokenProvider — always
  lines.push('    if (auth.kind === "tokenProvider") {');
  lines.push("      const token = await auth.getToken();");
  lines.push('      headers["Authorization"] = `Bearer ${token}`;');
  lines.push("    }");
  return lines;
}

function buildOnUnauthorized(hasOauth2: boolean): string {
  if (hasOauth2) {
    return [
      "  onUnauthorized(): boolean {",
      '    if (this.auth.kind === "oauth2" || this.auth.kind === "tokenProvider") {',
      "      this.invalidate();",
      "      return true;",
      "    }",
      "    return false;",
      "  }",
    ].join("\n");
  }
  return [
    "  onUnauthorized(): boolean {",
    '    if (this.auth.kind === "tokenProvider") {',
    "      return true;",
    "    }",
    "    return false;",
    "  }",
  ].join("\n");
}

function buildInvalidate(hasOauth2: boolean): string {
  if (!hasOauth2) return "";
  return [
    "  invalidate(): void {",
    "    this.cachedToken = null;",
    "    this.inflight = null;",
    "  }",
  ].join("\n");
}

function buildFetchToken(schemes: readonly AuthSchemeDescriptor[]): string {
  const oauth2 = schemes.find(
    (s): s is Extract<AuthSchemeDescriptor, { kind: "oauth2ClientCredentials" }> =>
      s.kind === "oauth2ClientCredentials",
  );
  const defaultUrl =
    oauth2?.tokenUrl != null ? `"${oauth2.tokenUrl}"` : "undefined";
  return buildGetOauth2Token(defaultUrl);
}

function buildGetOauth2Token(defaultUrl: string): string {
  return [
    "  private getOauth2Token(): Promise<string> {",
    "    const now = Date.now();",
    "    if (this.cachedToken && this.cachedToken.expiresAt > now) {",
    "      return Promise.resolve(this.cachedToken.token);",
    "    }",
    "    if (this.inflight) return this.inflight;",
    "    this.inflight = this.fetchOauth2Token(now);",
    "    this.inflight.finally(() => { this.inflight = null; });",
    "    return this.inflight;",
    "  }",
    "",
    "  private async fetchOauth2Token(now: number): Promise<string> {",
    '    if (this.auth.kind !== "oauth2") throw new ConfigError("auth kind mismatch");',
    `    const url = this.auth.tokenUrl ?? ${defaultUrl};`,
    '    if (!url) throw new ConfigError("tokenUrl is required for oauth2 but was not provided");',
    "    const { clientId, clientSecret } = this.auth;",
    "    const credentials = btoa(`${clientId}:${clientSecret}`);",
    "    const body = new URLSearchParams();",
    '    body.set("grant_type", "client_credentials");',
    "    const res = await this.fetchImpl(url, {",
    '      method: "POST",',
    '      headers: { "Authorization": `Basic ${credentials}`, "Content-Type": "application/x-www-form-urlencoded" },',
    "      body: body.toString(),",
    "    });",
    "    if (!res.ok) {",
    "      throw new AuthError(`token endpoint returned ${res.status}: ${url}`);",
    "    }",
    "    const json = await res.json() as Record<string, unknown>;",
    '    const token = json["access_token"];',
    '    if (typeof token !== "string") throw new AuthError("malformed token response");',
    '    const expires_in = typeof json["expires_in"] === "number" ? (json["expires_in"] as number) : undefined;',
    "    this.cachedToken = { token, expiresAt: now + (expires_in ?? 300) * 1000 - 60 * 1000 };",
    "    return token;",
    "  }",
  ].join("\n");
}
