// src/sdk-plugins/auth.ts
// Emits the auth.ts module: AuthConfig union, resolveAuthFromEnv (+ a baked
// REQUIRED_ENV_VARS list), and AuthManager. OAuth2 client-credentials token
// fetch uses the injected fetchImpl (never globalThis.fetch). Token cache:
// { token, expiresAt } + single-flight Promise.
//
// Line-array builders live in ./auth-emit.ts so this file stays under the
// 300-line house rule.

import type { AuthSchemeDescriptor } from "./runtime.js";
import { buildAuthManager, buildResolveAuthFromEnv } from "./auth-emit.js";

const HEADER = `// Auto-generated by @skillship/sdk-plugin-auth. Do not edit by hand.
import { AuthError, ConfigError } from "./errors.js";

// Narrow ambient so resolveAuthFromEnv compiles without @types/node — the
// emitted package ships zero dependencies and a DOM-only lib. At runtime this is
// the real Node \`process\`; in non-Node hosts env simply resolves to undefined.
declare const process: { env: Record<string, string | undefined> };`;

export function generateAuthModule(
  schemes: readonly AuthSchemeDescriptor[],
  envPrefix: string,
): string {
  return [
    HEADER,
    `export type AuthConfig = ${buildAuthUnion(schemes)};`,
    "",
    buildResolveAuthFromEnv(schemes, envPrefix),
    "",
    buildAuthManager(schemes),
  ].join("\n");
}

// ─── AuthConfig union ────────────────────────────────────────────────────────

function buildAuthUnion(schemes: readonly AuthSchemeDescriptor[]): string {
  const parts: string[] = [];
  const seen = new Set<string>();
  for (const s of schemes) {
    if (s.kind === "bearer" && !seen.has("bearer")) {
      seen.add("bearer");
      parts.push('{ kind: "bearer"; token: string }');
    } else if (s.kind === "apiKey" && !seen.has("apiKey")) {
      seen.add("apiKey");
      parts.push('{ kind: "apiKey"; value: string; in: "header" | "query"; name: string }');
    } else if (s.kind === "basic" && !seen.has("basic")) {
      seen.add("basic");
      parts.push('{ kind: "basic"; username: string; password: string }');
    } else if (s.kind === "oauth2ClientCredentials" && !seen.has("oauth2")) {
      seen.add("oauth2");
      parts.push(
        '{ kind: "oauth2"; clientId: string; clientSecret: string; tokenUrl?: string; scopes?: string[] }',
      );
    }
    // external: no union member
  }
  // tokenProvider is ALWAYS present
  parts.push('{ kind: "tokenProvider"; getToken: () => Promise<string> }');
  return parts.join(" | ");
}
