// src/sdk-plugins/entry.ts
// Generates the wedge barrel index.ts that exposes Client, attachResources,
// AuthConfig, ResourceTree, and all error classes as the package entry point.
// INTENTIONALLY does NOT re-export types.gen.ts — its Hey-API ClientOptions
// collides with runtime.ts's ClientOptions and would break the tsc gate.

export function generateEntryModule(): string {
  return [
    '// Auto-generated by skillship. Package entry exposes the wedge surface.',
    'export * from "./runtime.js";',
    'export * from "./errors.js";',
    'export * from "./resources.js";',
    '',
  ].join('\n')
}
