// src/sdk-plugins/errors.ts
// Hey API custom plugin: emits a typed error hierarchy and patches the
// SDK transport so non-2xx responses throw the right class.
//
// The plugin contract (factory shape, output dir, hooks) follows
// @hey-api/openapi-ts plugin authoring — see the SDK comment in
// src/renderers/sdk.ts for the pinned version.

const ERRORS_MODULE_SOURCE = `// Auto-generated by @skillship/sdk-plugin-errors. Do not edit by hand.

export class APIError extends Error {
  readonly status: number;
  readonly requestId: string | null;
  readonly body: unknown;
  readonly code: string | null;
  constructor(args: { status: number; requestId: string | null; body: unknown; code: string | null; message: string }) {
    super(args.message);
    this.name = "APIError";
    this.status = args.status;
    this.requestId = args.requestId;
    this.body = args.body;
    this.code = args.code;
  }
}

export class BadRequestError extends APIError { constructor(a: ConstructorParameters<typeof APIError>[0]) { super(a); this.name = "BadRequestError"; } }
export class UnauthorizedError extends APIError { constructor(a: ConstructorParameters<typeof APIError>[0]) { super(a); this.name = "UnauthorizedError"; } }
export class ForbiddenError extends APIError { constructor(a: ConstructorParameters<typeof APIError>[0]) { super(a); this.name = "ForbiddenError"; } }
export class NotFoundError extends APIError { constructor(a: ConstructorParameters<typeof APIError>[0]) { super(a); this.name = "NotFoundError"; } }
export class RateLimitError extends APIError { constructor(a: ConstructorParameters<typeof APIError>[0]) { super(a); this.name = "RateLimitError"; } }
export class InternalServerError extends APIError { constructor(a: ConstructorParameters<typeof APIError>[0]) { super(a); this.name = "InternalServerError"; } }

export function throwForResponse(args: { status: number; requestId: string | null; body: unknown; code: string | null }): never {
  const message = "API error " + String(args.status);
  switch (args.status) {
    case 400: throw new BadRequestError({ ...args, message });
    case 401: throw new UnauthorizedError({ ...args, message });
    case 403: throw new ForbiddenError({ ...args, message });
    case 404: throw new NotFoundError({ ...args, message });
    case 429: throw new RateLimitError({ ...args, message });
    default:
      if (args.status >= 500 && args.status <= 599) throw new InternalServerError({ ...args, message });
      throw new APIError({ ...args, message });
  }
}
`;

export function generateErrorsModule(): string {
  return ERRORS_MODULE_SOURCE;
}

export function dispatchClassForStatus(status: number): string {
  if (status === 400) return "BadRequestError";
  if (status === 401) return "UnauthorizedError";
  if (status === 403) return "ForbiddenError";
  if (status === 404) return "NotFoundError";
  if (status === 429) return "RateLimitError";
  if (status >= 500 && status <= 599) return "InternalServerError";
  return "APIError";
}

/**
 * Hey API plugin factory. The exact return shape is dictated by
 * @hey-api/openapi-ts's plugin authoring API at the pinned version.
 * Returns a plugin object the engine consumes during codegen.
 *
 * Implementation note: the factory just hands the engine the
 * `generateErrorsModule()` string and a single output filename
 * (`errors.ts`). The plugin contributes no other emit; the SDK
 * transport (emitted by `src/sdk-plugins/runtime.ts`) imports
 * `throwForResponse` from this file when handling non-2xx responses.
 */
export function errorsPlugin(): unknown {
  return {
    name: "@skillship/sdk-errors",
    output: "errors",
    handler: () => generateErrorsModule(),
  };
}
