// src/sdk-plugins/mcp-protocol.ts
// Emits the mcp-protocol.ts module: zero-dependency stdio JSON-RPC transport +
// MCP protocol handler. The emitted file owns the full MCP lifecycle:
// ambient process declaration, JsonRpcRequest/Response interfaces, ToolDef,
// ToolResult, PROTOCOL_VERSION, runStdioServer (newline-buffered stdin I/O),
// processLine (testable seam), and makeProtocolHandler (initialize/ping/
// tools/list/tools/call + error codes).
//
// Emission helpers are inline (no separate -emit.ts split) because the emitter
// source is exactly one function, which stays well under 300 lines.
//
// House rules: ≤50-line helpers, ≤300-line file, no `any`, explicit returns.

const EMITTED_HEADER = `\
// Auto-generated by @skillship/sdk-plugin-mcp-protocol. Do not edit by hand.

// Narrow ambient so this module compiles without @types/node — the emitted
// package ships zero dependencies and a DOM-only lib. At runtime this is the
// real Node \`process\`; type-stripping erases the declaration cleanly.
declare const process: {
  stdin: {
    setEncoding(enc: string): void;
    on(event: "data", listener: (chunk: string) => void): void;
    on(event: "end", listener: () => void): void;
    resume(): void;
  };
  stdout: { write(data: string): boolean };
  stderr: { write(data: string): boolean };
  exit(code: number): never;
  versions: { node: string };
};`;

function emitInterfaces(): string {
  return `
export interface JsonRpcRequest {
  readonly jsonrpc: "2.0";
  readonly id?: number | string | null;
  readonly method: string;
  readonly params?: Record<string, unknown>;
}

export interface JsonRpcResponse {
  readonly jsonrpc: "2.0";
  readonly id: number | string | null;
  readonly result?: unknown;
  readonly error?: { readonly code: number; readonly message: string };
}

export interface ToolDef {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Record<string, unknown>;
}

export interface ToolResult {
  readonly content: readonly [{ readonly type: "text"; readonly text: string }];
  readonly isError?: boolean;
}

export const PROTOCOL_VERSION = "2025-06-18";`;
}

function emitMakeError(): string {
  return `
function makeError(
  id: number | string | null,
  code: number,
  message: string,
): JsonRpcResponse {
  return { jsonrpc: "2.0", id, error: { code, message } };
}

function makeResult(id: number | string | null, result: unknown): JsonRpcResponse {
  return { jsonrpc: "2.0", id, result };
}`;
}

function emitProcessLine(): string {
  return `
export async function processLine(
  line: string,
  handler: (msg: JsonRpcRequest) => Promise<JsonRpcResponse | null>,
): Promise<string | null> {
  let msg: JsonRpcRequest;
  try {
    msg = JSON.parse(line) as JsonRpcRequest;
  } catch {
    const errResp = makeError(null, -32700, "Parse error");
    return JSON.stringify(errResp) + "\\n";
  }
  const response = await handler(msg);
  if (response === null) return null;
  return JSON.stringify(response) + "\\n";
}`;
}

function emitRunStdioServer(): string {
  return `
export function runStdioServer(
  handler: (msg: JsonRpcRequest) => Promise<JsonRpcResponse | null>,
): void {
  let buffer = "";
  process.stdin.setEncoding("utf8");
  process.stdin.on("data", (chunk: string) => {
    buffer += chunk;
    let idx: number;
    while ((idx = buffer.indexOf("\\n")) !== -1) {
      const line = buffer.slice(0, idx).trim();
      buffer = buffer.slice(idx + 1);
      if (line.length === 0) continue;
      processLine(line, handler).then((out) => {
        if (out !== null) process.stdout.write(out);
      }).catch((err: unknown) => {
        process.stderr.write(\`[mcp-protocol] unhandled error: \${String(err)}\\n\`);
      });
    }
  });
  process.stdin.on("end", () => {
    const trimmed = buffer.trim();
    if (trimmed.length > 0) {
      processLine(trimmed, handler).then((out) => {
        if (out !== null) process.stdout.write(out);
      }).catch((err: unknown) => {
        process.stderr.write(\`[mcp-protocol] unhandled error: \${String(err)}\\n\`);
      });
    }
  });
  process.stdin.resume();
}`;
}

function emitMakeProtocolHandler(): string {
  return `
export function makeProtocolHandler(opts: {
  serverName: string;
  serverVersion: string;
  tools: readonly ToolDef[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<ToolResult>;
}): (msg: JsonRpcRequest) => Promise<JsonRpcResponse | null> {
  const { serverName, serverVersion, tools, callTool } = opts;

  return async function handleRequest(
    msg: JsonRpcRequest,
  ): Promise<JsonRpcResponse | null> {
    const id: number | string | null = msg.id ?? null;

    if (msg.method === "initialize") {
      return makeResult(id, {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: { tools: {} },
        serverInfo: { name: serverName, version: serverVersion },
      });
    }

    if (msg.method === "notifications/initialized") {
      return null;
    }

    if (msg.method === "ping") {
      return makeResult(id, {});
    }

    if (msg.method === "tools/list") {
      return makeResult(id, { tools });
    }

    if (msg.method === "tools/call") {
      const params = msg.params;
      if (params === undefined || params === null) {
        return makeError(id, -32602, "Invalid params: params is required for tools/call");
      }
      const name = params["name"];
      if (typeof name !== "string") {
        return makeError(id, -32602, "Invalid params: name (string) is required");
      }
      const args =
        typeof params["arguments"] === "object" &&
        params["arguments"] !== null &&
        !Array.isArray(params["arguments"])
          ? (params["arguments"] as Record<string, unknown>)
          : {};
      const toolNames = tools.map((t) => t.name);
      if (!toolNames.includes(name)) {
        return makeResult(id, {
          content: [
            {
              type: "text",
              text: \`unknown tool '\${name}' — available: \${toolNames.join(", ")}\`,
            },
          ],
          isError: true,
        });
      }
      const toolResult = await callTool(name, args);
      return makeResult(id, toolResult);
    }

    return makeError(id, -32601, \`Method not found: \${msg.method}\`);
  };
}`;
}

export function generateMcpProtocolModule(): string {
  return [
    EMITTED_HEADER,
    emitInterfaces(),
    emitMakeError(),
    emitProcessLine(),
    emitRunStdioServer(),
    emitMakeProtocolHandler(),
    "",
  ].join("\n");
}
