// src/sdk-plugins/mcp-launcher.ts
// Emits the two launcher files that ship in the SDK package's bin/ directory:
//   bin/loader.mjs — the verified 17-line zero-dep ESM resolve hook that maps a
//                    relative `.js` specifier to its `.ts` sibling ONLY when the
//                    `.js` file is absent (S1b spike, byte-verbatim).
//   bin/mcp.js     — the stdio entry point: shebang, a Node ≥23.6 type-stripping
//                    floor gate (actionable stderr + exit 1), registers the
//                    loader, then dynamic-imports ../src/mcp-server.ts and calls
//                    main() (the emitted gateway does NOT auto-start at import).
//
// Both emitters are product-independent — they bake no per-product data — so the
// emitted files are byte-identical across every SDK tree. Nothing here runs at
// MCP server runtime; each export returns an EMITTED source string.

/**
 * Emits bin/loader.mjs byte-verbatim from the spike's verified resolve hook.
 * The trailing newline is intentional (POSIX text-file convention, matches the
 * prettier-normalized siblings).
 */
export function generateMcpLoaderModule(): string {
  return `import { existsSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

export async function resolve(specifier, context, nextResolve) {
  if (!specifier.startsWith(".") || !specifier.endsWith(".js")) {
    return nextResolve(specifier, context);
  }
  const resolved = new URL(specifier, context.parentURL ?? import.meta.url);
  const jsPath = fileURLToPath(resolved);
  if (!existsSync(jsPath)) {
    const tsPath = jsPath.replace(/\\.js$/, ".ts");
    if (existsSync(tsPath)) {
      return nextResolve(specifier.replace(/\\.js$/, ".ts"), context);
    }
  }
  return nextResolve(specifier, context);
}
`;
}

/**
 * Emits bin/mcp.js — the launcher invoked by the package's `bin` entry and by
 * the rendered .mcp.json (`node sdk/bin/mcp.js`). Version gate floor is 23.6.0
 * (default-on type stripping); below it `.ts` imports raise SyntaxError, so the
 * gate fails fast with a 3-line actionable message instead of a stack trace.
 */
export function generateMcpLauncherModule(): string {
  return `#!/usr/bin/env node
// Auto-generated by @skillship/sdk-plugin-mcp-launcher. Do not edit by hand.
// Launches the MCP stdio server. Requires Node >=23.6 (default-on TS stripping).
import { register } from "node:module";

const [major, minor] = process.versions.node.split(".").map(Number);
if (major < 23 || (major === 23 && minor < 6)) {
  process.stderr.write(
    "This MCP server requires Node >=23.6 (it runs TypeScript directly).\\n" +
      "You are on Node " +
      process.versions.node +
      ". Upgrade Node, then re-run this server.\\n" +
      "See https://nodejs.org for the latest LTS.\\n",
  );
  process.exit(1);
}

register("./loader.mjs", import.meta.url);

const mod = await import(new URL("../src/mcp-server.ts", import.meta.url).href);
mod.main();
`;
}
