// src/sdk-plugins/mcp-catalog-emit.ts
// Line-array emission helpers for mcp-catalog.ts.
// Split out so mcp-catalog.ts stays under the 300-line house rule.
//
// All exports produce EMITTED TypeScript strings; nothing here runs at MCP
// server runtime. The generated module is data-only: two interfaces + CATALOG const.

import type { CatalogEntry, CatalogParam } from "./mcp-catalog.js";

const HEADER = `// Auto-generated by @skillship/sdk-plugin-mcp-catalog. Do not edit by hand.`;

// Keep in sync with the interfaces in ./mcp-catalog.ts
const CATALOG_PARAM_INTERFACE = `export interface CatalogParam {
  readonly name: string;
  readonly in: "path" | "query" | "body";
  readonly type: string;
  readonly required: boolean;
}`;

// Keep in sync with the interfaces in ./mcp-catalog.ts
const CATALOG_ENTRY_INTERFACE = `export interface CatalogEntry {
  readonly id: string;
  readonly accessor: readonly [string, string];
  readonly httpMethod: string;
  readonly path: string;
  readonly summary: string;
  readonly description: string;
  readonly searchText: string;
  readonly params: readonly CatalogParam[];
  readonly annotations: {
    readonly destructive: boolean;
    readonly readOnly: boolean;
    readonly idempotent: boolean;
  };
  readonly paginated: boolean;
}`;

// ---- Indentation helpers ----

/** Returns a string of (n * 2) spaces. */
function ind(depth: number): string {
  return " ".repeat(depth * 2);
}

// ---- Literal serialization helpers ----

function serializeString(s: string): string {
  // Produce a JSON-safe double-quoted string literal
  return JSON.stringify(s);
}

function serializeBoolean(b: boolean): string {
  return b ? "true" : "false";
}

/**
 * Serialize a single CatalogParam.
 * itemDepth: the depth at which the param object's braces sit.
 * Fields sit one level deeper.
 *
 * For a top-level CATALOG entry (depth 1), entries' properties are at depth 2,
 * the params array items (param objects) are at depth 3, and param fields at depth 4.
 */
function serializeParam(p: CatalogParam, itemDepth: number): string {
  const o = ind(itemDepth);
  const f = ind(itemDepth + 1);
  return [
    `${o}{`,
    `${f}name: ${serializeString(p.name)},`,
    `${f}in: ${serializeString(p.in)},`,
    `${f}type: ${serializeString(p.type)},`,
    `${f}required: ${serializeBoolean(p.required)},`,
    `${o}}`,
  ].join("\n");
}

/**
 * Serialize the params array.
 * itemDepth: the depth of the param object braces (same as serializeParam's itemDepth).
 * The closing ] aligns with (itemDepth - 1).
 */
function serializeParams(params: readonly CatalogParam[], itemDepth: number): string {
  if (params.length === 0) return "[]";
  const closeIndent = ind(itemDepth - 1);
  const items = params.map((p) => serializeParam(p, itemDepth)).join(",\n");
  return `[\n${items},\n${closeIndent}]`;
}

/**
 * Serialize the annotations object (opened inline on the property line).
 * fieldDepth: the depth of the annotation field lines.
 * Closing brace sits one level up (fieldDepth - 1).
 */
function serializeAnnotations(a: CatalogEntry["annotations"], fieldDepth: number): string {
  const f = ind(fieldDepth);
  const c = ind(fieldDepth - 1);
  return [
    "{",
    `${f}destructive: ${serializeBoolean(a.destructive)},`,
    `${f}readOnly: ${serializeBoolean(a.readOnly)},`,
    `${f}idempotent: ${serializeBoolean(a.idempotent)},`,
    `${c}}`,
  ].join("\n");
}

function serializeEntry(e: CatalogEntry): string {
  // Entries sit at depth 1 (2-space indent).
  // Properties inside the entry sit at depth 2 (4-space indent).
  // Params array items (param objects) sit at depth 3 (6-space).
  // Param fields sit at depth 4 (8-space).
  // Annotations fields sit at depth 3 (6-space).
  // Annotations closing brace sits at depth 2 (4-space).
  const entryDepth = 1;
  const propDepth = entryDepth + 1;   // 2 → 4 spaces
  const itemDepth = propDepth + 1;    // 3 → 6 spaces (param objects, annotations fields)

  const o = ind(entryDepth);
  const p = ind(propDepth);
  return [
    `${o}{`,
    `${p}id: ${serializeString(e.id)},`,
    `${p}accessor: [${serializeString(e.accessor[0])}, ${serializeString(e.accessor[1])}] as const,`,
    `${p}httpMethod: ${serializeString(e.httpMethod)},`,
    `${p}path: ${serializeString(e.path)},`,
    `${p}summary: ${serializeString(e.summary)},`,
    `${p}description: ${serializeString(e.description)},`,
    `${p}searchText: ${serializeString(e.searchText)},`,
    `${p}params: ${serializeParams(e.params, itemDepth)},`,
    `${p}annotations: ${serializeAnnotations(e.annotations, itemDepth)},`,
    `${p}paginated: ${serializeBoolean(e.paginated)},`,
    `${o}}`,
  ].join("\n");
}

function serializeCatalog(entries: readonly CatalogEntry[]): string {
  if (entries.length === 0) {
    return "export const CATALOG: readonly CatalogEntry[] = [];";
  }
  const items = entries.map((e) => serializeEntry(e)).join(",\n");
  return `export const CATALOG: readonly CatalogEntry[] = [\n${items},\n];`;
}

// ---- Top-level emitter ----

export function emitCatalogModule(entries: readonly CatalogEntry[]): string {
  return [
    HEADER,
    "",
    CATALOG_PARAM_INTERFACE,
    "",
    CATALOG_ENTRY_INTERFACE,
    "",
    serializeCatalog(entries),
    "",
  ].join("\n");
}
