// src/sdk-plugins/mcp-server-emit.ts
// Structural line-array builders for the emitted src/mcp-server.ts (the MCP
// gateway): header/imports, the shared scorer, and createGateway/main. The
// callTool dispatch builders (tools, search, describe, invoke) live in
// ./mcp-server-dispatch.ts; both files import the shared `lit` from
// ./mcp-server-lit.ts so each stays under the 300-line house rule.
//
// Every export returns an EMITTED TypeScript string; nothing here runs at MCP
// server runtime. The emitted module is erasable TS, no `any`, explicit returns.
// Each builder is ≤50 lines of EMITTER source.

import { lit } from "./mcp-server-lit.js";

// ─── Header: imports + ambient process + GatewayDeps ──────────────────────────

export function buildHeader(): string {
  return `// Auto-generated by @skillship/sdk-plugin-mcp-server. Do not edit by hand.
import { CATALOG, type CatalogEntry } from "./mcp-catalog.js";
import {
  makeProtocolHandler,
  runStdioServer,
  type ToolDef,
  type ToolResult,
  type JsonRpcRequest,
  type JsonRpcResponse,
} from "./mcp-protocol.js";
import { Client } from "./runtime.js";
import { attachResources } from "./resources.js";

// Narrow ambient so this module compiles without @types/node — the emitted
// package ships zero dependencies and a DOM-only lib. The protocol module owns
// the wide transport shape; this module only reads env. The declaration is
// module-scoped, so the two ambients never collide.
declare const process: { env: Record<string, string | undefined> };

export interface GatewayDeps {
  readonly fetchImpl?: typeof fetch;
  readonly env?: Record<string, string | undefined>;
}

const MAX_RESULT_BYTES = 50000;`;
}

// ─── Scorer: tokenize + scoreEntry + closestIds ───────────────────────────────

export function buildScorer(): string {
  return `
function tokenize(s: string): readonly string[] {
  return s
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length > 0);
}

// Whole-token weighted score: id-tokens 4, summary 3, path 2, description 1.
function scoreEntry(entry: CatalogEntry, queryTokens: readonly string[]): number {
  const idTokens = new Set(entry.id.split("_").filter((t) => t.length > 0));
  const summaryTokens = new Set(tokenize(entry.summary));
  const pathTokens = new Set(tokenize(entry.path));
  const descTokens = new Set(tokenize(entry.description));
  let score = 0;
  for (const q of queryTokens) {
    if (idTokens.has(q)) score += 4;
    if (summaryTokens.has(q)) score += 3;
    if (pathTokens.has(q)) score += 2;
    if (descTokens.has(q)) score += 1;
  }
  return score;
}

// Closest ids to a bad id, by scoring CATALOG ids against the bad id's tokens.
function closestIds(badId: string, n: number): readonly string[] {
  const tokens = badId.split("_").filter((t) => t.length > 0);
  const scored = CATALOG.map((e) => {
    const ids = new Set(e.id.split("_").filter((t) => t.length > 0));
    let s = 0;
    for (const t of tokens) if (ids.has(t)) s += 1;
    return { id: e.id, s };
  });
  scored.sort((a, b) => (b.s - a.s) || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  return scored.slice(0, n).map((x) => x.id);
}

function findEntry(id: string): CatalogEntry | undefined {
  return CATALOG.find((e) => e.id === id);
}

function text(t: string, isError = false): ToolResult {
  return { content: [{ type: "text", text: t }], isError };
}`;
}

// ─── createGateway + main ─────────────────────────────────────────────────────

export function buildCreateGateway(productName: string, pkgVersion: string): string {
  const serverName = `${productName}-mcp`;
  return `
export function createGateway(
  deps?: GatewayDeps,
): (msg: JsonRpcRequest) => Promise<JsonRpcResponse | null> {
  const env = deps?.env ?? process.env;
  let cached: Gateway | null = null;
  const getClient = (): Gateway => {
    if (cached !== null) return cached;
    const baseUrl = resolveBaseUrl(env);
    if (baseUrl === null) throw new Error("base_url_not_set");
    cached = attachResources(
      new Client({ baseUrl, ...(deps?.fetchImpl ? { fetch: deps.fetchImpl } : {}) }),
    );
    return cached;
  };
  const callTool = (name: string, args: Record<string, unknown>): Promise<ToolResult> => {
    if (name === "search_operations") return Promise.resolve(runSearch(args));
    if (name === "describe_operation") return Promise.resolve(runDescribe(args));
    if (name === "invoke_operation") return runInvoke(args, env, getClient);
    return Promise.resolve(text("unknown tool: " + name, true));
  };
  return makeProtocolHandler({
    serverName: ${lit(serverName)},
    serverVersion: ${lit(pkgVersion)},
    tools: TOOLS,
    callTool,
  });
}`;
}

export function buildMain(): string {
  return `
export function main(): void {
  runStdioServer(createGateway());
}`;
}
