// src/sdk-plugins/mcp-catalog-emit.ts
// Line-array emission helpers for mcp-catalog.ts.
// Split out so mcp-catalog.ts stays under the 300-line house rule.
//
// All exports produce EMITTED TypeScript strings; nothing here runs at MCP
// server runtime. The generated module is data-only: two interfaces + CATALOG const.

import type { CatalogEntry, CatalogParam } from "./mcp-catalog.js";

const HEADER = `// Auto-generated by @skillship/sdk-plugin-mcp-catalog. Do not edit by hand.`;

const CATALOG_PARAM_INTERFACE = `export interface CatalogParam {
  readonly name: string;
  readonly in: "path" | "query" | "body";
  readonly type: string;
  readonly required: boolean;
}`;

const CATALOG_ENTRY_INTERFACE = `export interface CatalogEntry {
  readonly id: string;
  readonly accessor: readonly [string, string];
  readonly httpMethod: string;
  readonly path: string;
  readonly summary: string;
  readonly description: string;
  readonly searchText: string;
  readonly params: readonly CatalogParam[];
  readonly annotations: {
    readonly destructive: boolean;
    readonly readOnly: boolean;
    readonly idempotent: boolean;
  };
  readonly paginated: boolean;
}`;

// ---- Literal serialization helpers ----

function serializeString(s: string): string {
  // Produce a JSON-safe double-quoted string literal
  return JSON.stringify(s);
}

function serializeBoolean(b: boolean): string {
  return b ? "true" : "false";
}

function serializeParam(p: CatalogParam): string {
  return [
    "    {",
    `      name: ${serializeString(p.name)},`,
    `      in: ${serializeString(p.in)},`,
    `      type: ${serializeString(p.type)},`,
    `      required: ${serializeBoolean(p.required)},`,
    "    }",
  ].join("\n");
}

function serializeParams(params: readonly CatalogParam[]): string {
  if (params.length === 0) return "[]";
  const items = params.map((p) => serializeParam(p)).join(",\n");
  return `[\n${items},\n  ]`;
}

function serializeAnnotations(a: CatalogEntry["annotations"]): string {
  return [
    "{",
    `      destructive: ${serializeBoolean(a.destructive)},`,
    `      readOnly: ${serializeBoolean(a.readOnly)},`,
    `      idempotent: ${serializeBoolean(a.idempotent)},`,
    "    }",
  ].join("\n    ");
}

function serializeEntry(e: CatalogEntry): string {
  return [
    "  {",
    `    id: ${serializeString(e.id)},`,
    `    accessor: [${serializeString(e.accessor[0])}, ${serializeString(e.accessor[1])}] as const,`,
    `    httpMethod: ${serializeString(e.httpMethod)},`,
    `    path: ${serializeString(e.path)},`,
    `    summary: ${serializeString(e.summary)},`,
    `    description: ${serializeString(e.description)},`,
    `    searchText: ${serializeString(e.searchText)},`,
    `    params: ${serializeParams(e.params)},`,
    `    annotations: ${serializeAnnotations(e.annotations)},`,
    `    paginated: ${serializeBoolean(e.paginated)},`,
    "  }",
  ].join("\n");
}

function serializeCatalog(entries: readonly CatalogEntry[]): string {
  if (entries.length === 0) {
    return "export const CATALOG: readonly CatalogEntry[] = [];";
  }
  const items = entries.map((e) => serializeEntry(e)).join(",\n");
  return `export const CATALOG: readonly CatalogEntry[] = [\n${items},\n];`;
}

// ---- Top-level emitter ----

export function emitCatalogModule(entries: readonly CatalogEntry[]): string {
  return [
    HEADER,
    "",
    CATALOG_PARAM_INTERFACE,
    "",
    CATALOG_ENTRY_INTERFACE,
    "",
    serializeCatalog(entries),
    "",
  ].join("\n");
}
