// src/sdk-plugins/pagination.ts
// Emits the pagination.ts module: a generic async-generator engine that drives
// cursor, offset, and page-based pagination through any Client.request() call.
//
// Design decisions:
// - No imports from other generated modules (./errors, ./runtime, etc.) so the
//   emitted file is self-contained and dependency-free.
// - Missing itemsField throws a plain `TypeError` (not APIError) because it is a
//   programming error at SDK construction time, not a network error. The message
//   names both opId and fieldName so the developer can pinpoint the bad bake-in.
// - Yielded items are typed `unknown` — response schemas may be absent or loose;
//   precise typing requires schema-aware codegen (out of scope for T7).
// - pageSizeParam null handling: when pageSizeParam is null we cannot compare
//   received vs requested count; stopping on empty page only is the safe default.

const HEADER = `// Auto-generated by @skillship/sdk-plugin-pagination. Do not edit by hand.`;

const PAGINATE_PLAN_TYPE = `interface PaginatePlan {
  style: "cursor" | "offset" | "page";
  requestParam: string;
  pageSizeParam: string | null;
  itemsField: string;
  nextField: string | null;
  opId: string;
}`;

const PAGINATE_CURSOR = `async function* paginateCursor<Item>(
  fetchPage: (pageArgs: Record<string, unknown>) => Promise<unknown>,
  plan: PaginatePlan,
): AsyncGenerator<Item> {
  let prev: unknown = undefined;
  let cursor: unknown = undefined;
  for (;;) {
    const pageArgs: Record<string, unknown> = cursor != null ? { [plan.requestParam]: cursor } : {};
    const body = await fetchPage(pageArgs);
    if (typeof body !== "object" || body === null) return;
    const record = body as Record<string, unknown>;
    const items = record[plan.itemsField];
    if (!Array.isArray(items)) {
      throw new TypeError(
        \`paginate(\${plan.opId}): response body missing array field "\${plan.itemsField}"\`,
      );
    }
    if (items.length === 0) return;
    for (const item of items) yield item as Item;
    const nextField = plan.nextField;
    if (nextField === null) return;
    const next = record[nextField];
    if (next == null || next === "") return;
    if (next === prev) return;
    prev = cursor;
    cursor = next;
  }
}`;

const PAGINATE_OFFSET_PAGE = `async function* paginateOffsetOrPage<Item>(
  fetchPage: (pageArgs: Record<string, unknown>) => Promise<unknown>,
  plan: PaginatePlan,
): AsyncGenerator<Item> {
  let counter = 0;
  for (;;) {
    const pageArgs: Record<string, unknown> = { [plan.requestParam]: counter };
    const body = await fetchPage(pageArgs);
    if (typeof body !== "object" || body === null) return;
    const record = body as Record<string, unknown>;
    const items = record[plan.itemsField];
    if (!Array.isArray(items)) {
      throw new TypeError(
        \`paginate(\${plan.opId}): response body missing array field "\${plan.itemsField}"\`,
      );
    }
    if (items.length === 0) return;
    for (const item of items) yield item as Item;
    const pageSize = plan.pageSizeParam !== null ? (pageArgs[plan.pageSizeParam] as number | undefined) : undefined;
    if (pageSize !== undefined && items.length < pageSize) return;
    counter += plan.style === "page" ? 1 : items.length;
  }
}`;

const PAGINATE_EXPORT = `export async function* paginate<Item>(
  fetchPage: (pageArgs: Record<string, unknown>) => Promise<unknown>,
  plan: PaginatePlan,
): AsyncGenerator<Item> {
  if (plan.style === "cursor") {
    yield* paginateCursor<Item>(fetchPage, plan);
  } else {
    yield* paginateOffsetOrPage<Item>(fetchPage, plan);
  }
}`;

/**
 * Generates the pagination.ts source: a generic async-generator engine
 * (`paginate<Item>`) for cursor, offset, and page-based pagination.
 * The emitted file has no imports from other generated modules.
 */
export function generatePaginationModule(): string {
  return [
    HEADER,
    "",
    PAGINATE_PLAN_TYPE,
    "",
    PAGINATE_CURSOR,
    "",
    PAGINATE_OFFSET_PAGE,
    "",
    PAGINATE_EXPORT,
    "",
  ].join("\n");
}
