// src/sdk-plugins/resource-tree.ts
// Hey API custom plugin: reshapes generated client into nested namespaces.
//
// Data source contract (locked in spec §5.3):
//   The plugin reads resources rename/namespace rules from the CodegenOverlay
//   object passed through the plugin factory closure. The x-skillship-codegen
//   vendor extension on the OAS doc is INFORMATIONAL and NOT re-parsed here.
//   Single source of truth: the CodegenOverlay Zod-validated object.
//
// Fallback when no overlay rule matches: use the operation's tags[0],
// which R-OAS derives from the REST path's first non-template segment
// or the GraphQL root type (per renderers/oas.ts buildTags).
//
// If tags[0] is also absent, the op lands under "default".
import type { CodegenOverlay } from "../overlays/codegen.js";

export interface OperationInfo {
  readonly operationId: string;
  readonly tags: readonly string[];
}

export function buildNamespaceTree(
  ops: readonly OperationInfo[],
  overlay: CodegenOverlay,
): Record<string, string[]> {
  const tree: Record<string, string[]> = {};
  for (const op of ops) {
    const rule = overlay.resources[op.operationId];
    const namespace = rule?.namespace ?? op.tags[0] ?? "default";
    const methodName = rule?.rename ?? op.operationId;
    (tree[namespace] ??= []).push(methodName);
  }
  const sorted: Record<string, string[]> = {};
  for (const k of Object.keys(tree).sort()) sorted[k] = tree[k]!;
  return sorted;
}

/**
 * Generates the index.ts content that re-exports flat SDK functions
 * under nested namespaces. The flat functions come from
 * @hey-api/sdk's emit. We wire them into a Client extension:
 *
 *   client.projects.list(...) → calls listProjects(...)
 *
 * @param tree     The namespace tree from buildNamespaceTree.
 * @param hyaPath  The relative import path to the flat SDK module
 *                 emitted by @hey-api/sdk (typically "./sdk.gen.js").
 */
export function generateResourceTreeModule(
  tree: Record<string, string[]>,
  hyaPath: string,
): string {
  const lines: string[] = [];
  lines.push("// Auto-generated by @skillship/sdk-plugin-resource-tree. Do not edit by hand.");
  lines.push(`import * as flat from "${hyaPath}";`);
  lines.push(`import { Client } from "./runtime.js";`);
  lines.push("");
  lines.push("export interface ResourceTree {");
  for (const ns of Object.keys(tree)) {
    lines.push(`  readonly ${ns}: { ${tree[ns]!.map(m => `${m}: typeof flat.${m}`).join("; ")} };`);
  }
  lines.push("}");
  lines.push("");
  lines.push("export function attachResources(client: Client): Client & ResourceTree {");
  lines.push("  return Object.assign(client, {");
  for (const ns of Object.keys(tree)) {
    lines.push(`    ${ns}: { ${tree[ns]!.map(m => `${m}: flat.${m}`).join(", ")} },`);
  }
  lines.push("  });");
  lines.push("}");
  return lines.join("\n") + "\n";
}

export function resourceTreePlugin(overlay: CodegenOverlay): unknown {
  return {
    name: "@skillship/sdk-resource-tree",
    output: "resources",
    handler: (ctx: { operations: readonly OperationInfo[] }) => {
      const tree = buildNamespaceTree(ctx.operations, overlay);
      return generateResourceTreeModule(tree, "./sdk.gen.js");
    },
  };
}
