// src/sdk-plugins/runtime-emit.ts
// String-emission helpers for runtime.ts. Split out so the runtime.ts emitter
// source stays under the 300-line house rule (mirrors auth.ts/auth-emit.ts and
// resource-tree.ts/resource-tree-pages.ts).
//
// Each function returns a block of EMITTED TypeScript. None run at SDK runtime.
// The emitted Client delegates auth header injection to AuthManager.applyAuth
// (auth.ts owns the AuthConfig union) and drives the retry loop described in the
// runtime contract: full-jitter backoff, optional Retry-After, method-class
// retryability, fresh Request per attempt, single auth-refresh outside the
// retry counter.

import type { RetriesConfig } from "./runtime.js";

export function emitHeader(): string {
  return [
    "// Auto-generated by @skillship/sdk-plugin-runtime. Do not edit by hand.",
    'import { throwForResponse, TimeoutError, UnauthorizedError, ConfigError } from "./errors.js";',
    'import { AuthManager, resolveAuthFromEnv, REQUIRED_ENV_VARS, type AuthConfig } from "./auth.js";',
    "",
    'export type { AuthConfig } from "./auth.js";',
  ].join("\n");
}

export function emitConstants(retries: RetriesConfig): string {
  const statusLiteral = `[${retries.retryableStatus.join(", ")}]`;
  return [
    "",
    `const MAX_RETRIES = ${retries.maxRetries};`,
    `const RETRYABLE_STATUS: readonly number[] = ${statusLiteral};`,
    "const BASE_DELAY_MS = 500;",
    "const MAX_DELAY_MS = 30000;",
    `const HONOR_RETRY_AFTER = ${retries.honorRetryAfter};`,
    'const IDEMPOTENT_METHODS: readonly string[] = ["GET", "HEAD", "PUT", "DELETE", "OPTIONS"];',
    "// Non-idempotent methods (POST/PATCH) retry ONLY these statuses, never network errors or timeouts.",
    "const NON_IDEMPOTENT_RETRYABLE: readonly number[] = [408, 429];",
  ].join("\n");
}

export function emitDefaultSleep(): string {
  return [
    "",
    "function defaultSleep(ms: number): Promise<void> {",
    "  return new Promise((resolve) => setTimeout(resolve, ms));",
    "}",
  ].join("\n");
}

export function emitClientOptions(): string {
  return [
    "",
    "export interface ClientOptions {",
    "  baseUrl: string;",
    "  auth?: AuthConfig;",
    "  defaultHeaders?: Record<string, string>;",
    "  fetch?: typeof fetch;",
    "  timeout?: number;",
    "  sleep?: (ms: number) => Promise<void>;",
    "  onRequest?: (req: Request) => Request | Promise<Request>;",
    "  onResponse?: (res: Response) => Response | Promise<Response>;",
    "}",
  ].join("\n");
}

export function emitClassOpen(): string {
  return [
    "",
    "export class Client {",
    "  readonly baseUrl: string;",
    "  readonly defaultHeaders: Record<string, string>;",
    "  readonly fetchImpl: typeof fetch;",
    "  readonly timeout: number | undefined;",
    "  readonly sleep: (ms: number) => Promise<void>;",
    "  readonly onRequest: ((req: Request) => Request | Promise<Request>) | undefined;",
    "  readonly onResponse: ((res: Response) => Response | Promise<Response>) | undefined;",
    "  private readonly authManager: AuthManager;",
  ].join("\n");
}

export function emitConstructor(): string {
  return [
    "",
    "  constructor(opts: ClientOptions) {",
    '    this.baseUrl = opts.baseUrl.replace(/\\/+$/, "") + "/";',
    "    this.defaultHeaders = opts.defaultHeaders ?? {};",
    "    this.fetchImpl = opts.fetch ?? globalThis.fetch;",
    "    this.timeout = opts.timeout;",
    "    this.sleep = opts.sleep ?? defaultSleep;",
    "    this.onRequest = opts.onRequest;",
    "    this.onResponse = opts.onResponse;",
    "    // Resolve auth: explicit option > environment > ConfigError listing env vars.",
    "    const auth = opts.auth ?? resolveAuthFromEnv();",
    "    if (auth === null) {",
    '      const names = REQUIRED_ENV_VARS.join(", ");',
    "      throw new ConfigError(`no auth configured: pass the 'auth' option or set ${names}`);",
    "    }",
    "    this.authManager = new AuthManager(auth, this.fetchImpl);",
    "  }",
  ].join("\n");
}

export function emitRequestMethod(): string {
  return [
    "",
    "  async request(input: { path: string; method: string; pathParams?: Record<string, string | number>; query?: Record<string, string | number | boolean | undefined>; body?: unknown; headers?: Record<string, string> }): Promise<Response> {",
    "    return this.executeWithAuthRefresh(input);",
    "  }",
  ].join("\n");
}

export function emitBuildRequest(): string {
  // Builds the per-attempt URL + base headers. Auth is applied separately (once
  // per auth-refresh pass) because a 401 refresh must re-inject credentials.
  return [
    "",
    "  private buildTarget(input: { path: string; pathParams?: Record<string, string | number>; query?: Record<string, string | number | boolean | undefined>; headers?: Record<string, string> }): { url: URL; headers: Record<string, string> } {",
    "    let resolvedPath = input.path;",
    "    if (input.pathParams) {",
    "      for (const [k, v] of Object.entries(input.pathParams)) {",
    "        resolvedPath = resolvedPath.replaceAll(`{${k}}`, encodeURIComponent(String(v)));",
    "      }",
    "    }",
    '    const relPath = resolvedPath.startsWith("/") ? resolvedPath.slice(1) : resolvedPath;',
    "    const url = new URL(relPath, this.baseUrl);",
    "    if (input.query) {",
    "      for (const [k, v] of Object.entries(input.query)) {",
    "        if (v !== undefined) url.searchParams.append(k, String(v));",
    "      }",
    "    }",
    "    const headers: Record<string, string> = { ...this.defaultHeaders, ...(input.headers ?? {}) };",
    "    return { url, headers };",
    "  }",
  ].join("\n");
}

export function emitExecuteWithAuthRefresh(): string {
  // Single auth refresh OUTSIDE the retry counter: a 401 that AuthManager can
  // recover from invalidates the cache, re-applies auth, and re-runs the retry
  // loop exactly once. A second 401 surfaces as UnauthorizedError.
  return [
    "",
    "  private async executeWithAuthRefresh(input: { path: string; method: string; pathParams?: Record<string, string | number>; query?: Record<string, string | number | boolean | undefined>; body?: unknown; headers?: Record<string, string> }): Promise<Response> {",
    "    let refreshed = false;",
    "    for (;;) {",
    "      const { url, headers } = this.buildTarget(input);",
    "      await this.authManager.applyAuth(headers, url.searchParams);",
    "      const res = await this.runRetryLoop(input.method, url, headers, input.body);",
    "      if (res.status === 401 && !refreshed && this.authManager.onUnauthorized()) {",
    "        refreshed = true;",
    "        continue;",
    "      }",
    "      return this.finalize(res);",
    "    }",
    "  }",
    "",
    "  private async finalize(res: Response): Promise<Response> {",
    "    let out = res;",
    "    if (this.onResponse) out = await this.onResponse(out);",
    "    if (!out.ok) {",
    '      const requestId = out.headers.get("x-request-id");',
    "      let body: unknown = null;",
    "      try { body = await out.clone().json(); } catch { try { body = await out.clone().text(); } catch { /* ignore */ } }",
    "      // A 401 that reaches finalize survived the single auth-refresh retry.",
    "      if (out.status === 401) {",
    '        throw new UnauthorizedError({ status: 401, requestId, body, code: null, message: "API error 401" });',
    "      }",
    "      throwForResponse({ status: out.status, requestId, body, code: null });",
    "    }",
    "    return out;",
    "  }",
  ].join("\n");
}

export function emitRequestLoop(): string {
  // Drives the retry counter. onResponse runs ONLY in finalize (on the returned
  // response), never here. A fresh Request is built every attempt so single-use
  // bodies are re-serialized cleanly.
  return [
    "",
    "  private async runRetryLoop(method: string, url: URL, headers: Record<string, string>, body: unknown): Promise<Response> {",
    "    const idempotent = IDEMPOTENT_METHODS.includes(method.toUpperCase());",
    "    let lastError: unknown = null;",
    "    let lastResponse: Response | null = null;",
    "    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {",
    "      const controller = new AbortController();",
    "      const timeoutId = this.timeout !== undefined ? setTimeout(() => controller.abort(), this.timeout) : null;",
    "      const init: RequestInit = { method, headers, signal: controller.signal };",
    "      if (body !== undefined) {",
    '        headers["Content-Type"] = headers["Content-Type"] ?? "application/json";',
    "        init.body = JSON.stringify(body);",
    "      }",
    "      let req = new Request(url.toString(), init);",
    "      try {",
    "        if (this.onRequest) req = await this.onRequest(req);",
    "        const res = await this.fetchImpl(req);",
    "        lastResponse = res;",
    "        if (attempt < MAX_RETRIES && this.shouldRetryStatus(res.status, idempotent)) {",
    "          await this.sleep(this.computeDelay(attempt, res));",
    "          continue;",
    "        }",
    "        return res;",
    "      } catch (err) {",
    "        const timedOut = controller.signal.aborted;",
    '        lastError = timedOut ? new TimeoutError({ status: 0, requestId: null, body: null, code: "timeout", message: `Request timed out after ${this.timeout}ms` }) : err;',
    "        if (attempt < MAX_RETRIES && idempotent) {",
    "          await this.sleep(this.computeDelay(attempt, null));",
    "          continue;",
    "        }",
    "        throw this.exhausted(lastError, attempt + 1);",
    "      } finally {",
    "        if (timeoutId !== null) clearTimeout(timeoutId);",
    "      }",
    "    }",
    "    if (lastResponse !== null) return lastResponse;",
    "    throw this.exhausted(lastError, MAX_RETRIES + 1);",
    "  }",
  ].join("\n");
}

export function emitBackoff(): string {
  // Full-jitter backoff with optional Retry-After override.
  return [
    "",
    "  private computeDelay(attempt: number, res: Response | null): number {",
    "    const cap = Math.min(MAX_DELAY_MS, BASE_DELAY_MS * 2 ** attempt);",
    "    const backoff = Math.random() * cap;",
    "    if (HONOR_RETRY_AFTER && res !== null) {",
    '      const ra = this.parseRetryAfter(res.headers.get("retry-after"));',
    "      if (ra !== null) return Math.min(ra, MAX_DELAY_MS);",
    "    }",
    "    return backoff;",
    "  }",
  ].join("\n");
}

export function emitRetryAfter(): string {
  return [
    "",
    "  private parseRetryAfter(header: string | null): number | null {",
    "    if (header === null) return null;",
    "    const trimmed = header.trim();",
    '    if (trimmed === "") return null;',
    "    if (/^\\d+$/.test(trimmed)) return Number(trimmed) * 1000;",
    "    const dateMs = Date.parse(trimmed);",
    "    if (!Number.isNaN(dateMs)) {",
    "      const delta = dateMs - Date.now();",
    "      return delta > 0 ? delta : 0;",
    "    }",
    "    // Unparseable Retry-After → caller falls back to the computed backoff.",
    "    return null;",
    "  }",
  ].join("\n");
}

export function emitRetryability(): string {
  return [
    "",
    "  private shouldRetryStatus(status: number, idempotent: boolean): boolean {",
    "    if (status === 401) return false;",
    "    const set = idempotent ? RETRYABLE_STATUS : NON_IDEMPOTENT_RETRYABLE;",
    "    return set.includes(status);",
    "  }",
    "",
    "  private exhausted(error: unknown, attempts: number): unknown {",
    "    if (error instanceof Error) {",
    "      error.message = `${error.message} (after ${attempts} attempts)`;",
    "      return error;",
    "    }",
    '    return new TimeoutError({ status: 0, requestId: null, body: null, code: "exhausted", message: `request failed (after ${attempts} attempts)` });',
    "  }",
  ].join("\n");
}
