// src/sdk-plugins/runtime.ts
// Hey API custom plugin: emits the Client class, fetch wrapper, and
// auth-injection logic. Auth schemes are projected from the synthetic
// OpenAPI's components.securitySchemes (via Plan 1/1.5 substrate).
//
// No retries / no backoff / no idempotency-key in Plan 2 — see spec §5.3
// and §5.10. Those land in Plan 2b with the retries plugin.

export type AuthSchemeDescriptor =
  | { readonly kind: "bearer"; readonly id: string }
  | { readonly kind: "apiKey"; readonly id: string; readonly in: "header" | "query"; readonly name: string }
  | { readonly kind: "basic"; readonly id: string }
  | { readonly kind: "oauth2ClientCredentials"; readonly id: string; readonly tokenUrl: string | null; readonly scopes: readonly string[] }
  | { readonly kind: "external"; readonly id: string; readonly schemeType: string };

export function generateRuntimeModule(schemes: readonly AuthSchemeDescriptor[]): string {
  const authUnion = buildAuthUnion(schemes);
  const injectBody = buildInjectBody(schemes);
  return `// Auto-generated by @skillship/sdk-plugin-runtime. Do not edit by hand.
import { throwForResponse, TimeoutError } from "./errors.js";

export type AuthConfig = ${authUnion};

export interface ClientOptions {
  baseUrl: string;
  auth: AuthConfig;
  defaultHeaders?: Record<string, string>;
  fetch?: typeof fetch;
  timeout?: number;
  onRequest?: (req: Request) => Request | Promise<Request>;
  onResponse?: (res: Response) => Response | Promise<Response>;
}

export class Client {
  readonly baseUrl: string;
  readonly auth: AuthConfig;
  readonly defaultHeaders: Record<string, string>;
  readonly fetchImpl: typeof fetch;
  readonly timeout: number | undefined;
  readonly onRequest: ((req: Request) => Request | Promise<Request>) | undefined;
  readonly onResponse: ((res: Response) => Response | Promise<Response>) | undefined;

  constructor(opts: ClientOptions) {
    // Normalize baseUrl to end with exactly one trailing slash for safe relative URL resolution.
    this.baseUrl = opts.baseUrl.replace(/\\/+$/, "") + "/";
    this.auth = opts.auth;
    this.defaultHeaders = opts.defaultHeaders ?? {};
    this.fetchImpl = opts.fetch ?? globalThis.fetch;
    this.timeout = opts.timeout;
    this.onRequest = opts.onRequest;
    this.onResponse = opts.onResponse;
  }

  async request(input: { path: string; method: string; pathParams?: Record<string, string | number>; query?: Record<string, string | number | boolean | undefined>; body?: unknown; headers?: Record<string, string> }): Promise<Response> {
    // Substitute path parameters (e.g. {id}) with encoded values before URL construction.
    let resolvedPath = input.path;
    if (input.pathParams) {
      for (const [k, v] of Object.entries(input.pathParams)) {
        resolvedPath = resolvedPath.replaceAll(\`{\${k}}\`, encodeURIComponent(String(v)));
      }
    }
    // Strip a single leading slash from path so URL() resolves it as relative to baseUrl.
    const relPath = resolvedPath.startsWith("/") ? resolvedPath.slice(1) : resolvedPath;
    const url = new URL(relPath, this.baseUrl);
    if (input.query) {
      for (const [k, v] of Object.entries(input.query)) {
        if (v !== undefined) url.searchParams.append(k, String(v));
      }
    }
    const headers: Record<string, string> = { ...this.defaultHeaders, ...(input.headers ?? {}) };
    const searchParams = url.searchParams;
${injectBody}
    const init: RequestInit = { method: input.method, headers };
    if (input.body !== undefined) {
      headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
      init.body = JSON.stringify(input.body);
    }
    const controller = new AbortController();
    const timeoutId = this.timeout !== undefined ? setTimeout(() => controller.abort(), this.timeout) : null;
    init.signal = controller.signal;
    let req = new Request(url.toString(), init);
    try {
      if (this.onRequest) req = await this.onRequest(req);
      let res = await this.fetchImpl(req);
      if (this.onResponse) res = await this.onResponse(res);
      if (!res.ok) {
        const requestId = res.headers.get("x-request-id");
        let body: unknown = null;
        try { body = await res.clone().json(); } catch { try { body = await res.clone().text(); } catch { /* ignore */ } }
        throwForResponse({ status: res.status, requestId, body, code: null });
      }
      return res;
    } catch (err) {
      // Only the internal timeout aborts this controller, so an abort here means a timeout.
      if (controller.signal.aborted) {
        throw new TimeoutError({ status: 0, requestId: null, body: null, code: "timeout", message: \`Request timed out after \${this.timeout}ms\` });
      }
      throw err;
    } finally {
      if (timeoutId !== null) clearTimeout(timeoutId);
    }
  }
}
`;
}

function buildAuthUnion(schemes: readonly AuthSchemeDescriptor[]): string {
  if (schemes.length === 0) return '{ readonly kind: "none" }';
  const parts = new Set<string>();
  for (const s of schemes) {
    if (s.kind === "bearer") parts.add('{ kind: "bearer"; token: string }');
    if (s.kind === "apiKey") parts.add('{ kind: "apiKey"; value: string; in: "header" | "query"; name: string }');
    if (s.kind === "basic") parts.add('{ kind: "basic"; username: string; password: string }');
    // oauth2ClientCredentials and external are inert until Task 8 — no union member emitted yet
  }
  // If all descriptors are new/inert kinds, fall back to the none sentinel to
  // prevent emitting `export type AuthConfig = ;` (a tsc-gate failure).
  if (parts.size === 0) return '{ readonly kind: "none" }';
  return [...parts].sort().join(" | ");
}

function buildInjectBody(schemes: readonly AuthSchemeDescriptor[]): string {
  // All auth branches emit `headers[...] = ...` assignments for consistency.
  if (schemes.length === 0) return "    // no auth schemes projected";
  const lines: string[] = [];
  // C2: guard bearer branch so apiKey/basic-only specs don't emit an invalid type check
  if (schemes.some((s) => s.kind === "bearer")) {
    lines.push('    if (this.auth.kind === "bearer") {');
    lines.push('      headers["Authorization"] = `Bearer ${this.auth.token}`;');
    lines.push('    }');
  }
  if (schemes.some((s) => s.kind === "apiKey")) {
    lines.push('    if (this.auth.kind === "apiKey") {');
    lines.push('      const value = this.auth.value;');
    lines.push('      if (this.auth.in === "header") headers[this.auth.name] = value;');
    lines.push('      else searchParams.append(this.auth.name, value);');
    lines.push('    }');
  }
  if (schemes.some((s) => s.kind === "basic")) {
    lines.push('    if (this.auth.kind === "basic") {');
    lines.push('      const encoded = btoa(`${this.auth.username}:${this.auth.password}`);');
    lines.push('      headers["Authorization"] = `Basic ${encoded}`;');
    lines.push('    }');
  }
  // oauth2ClientCredentials and external: inert in this task — no injection emitted until Task 8
  if (lines.length === 0) return "    // no active auth schemes projected";
  return lines.join("\n");
}
