// src/sdk-plugins/runtime.ts
// Hey API custom plugin: emits the Client class, fetch wrapper, and
// auth-injection logic. Auth schemes are projected from the synthetic
// OpenAPI's components.securitySchemes (via Plan 1/1.5 substrate).
//
// No retries / no backoff / no idempotency-key in Plan 2 — see spec §5.3
// and §5.10. Those land in Plan 2b with the retries plugin.

export type AuthSchemeDescriptor =
  | { readonly kind: "bearer"; readonly id: string }
  | { readonly kind: "apiKey"; readonly id: string; readonly in: "header" | "query"; readonly name: string }
  | { readonly kind: "basic"; readonly id: string };

export function generateRuntimeModule(schemes: readonly AuthSchemeDescriptor[]): string {
  const authUnion = buildAuthUnion(schemes);
  const injectBody = buildInjectBody(schemes);
  return `// Auto-generated by @skillship/sdk-plugin-runtime. Do not edit by hand.
import { throwForResponse } from "./errors.js";

export type AuthConfig = ${authUnion};

export interface ClientOptions {
  baseUrl: string;
  auth: AuthConfig;
  defaultHeaders?: Record<string, string>;
  fetch?: typeof fetch;
  timeout?: number;
  onRequest?: (req: Request) => Request | Promise<Request>;
  onResponse?: (res: Response) => Response | Promise<Response>;
}

export class Client {
  readonly baseUrl: string;
  readonly auth: AuthConfig;
  readonly defaultHeaders: Record<string, string>;
  readonly fetchImpl: typeof fetch;
  readonly timeout: number | undefined;
  readonly onRequest: ((req: Request) => Request | Promise<Request>) | undefined;
  readonly onResponse: ((res: Response) => Response | Promise<Response>) | undefined;

  constructor(opts: ClientOptions) {
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "");
    this.auth = opts.auth;
    this.defaultHeaders = opts.defaultHeaders ?? {};
    this.fetchImpl = opts.fetch ?? globalThis.fetch;
    this.timeout = opts.timeout;
    this.onRequest = opts.onRequest;
    this.onResponse = opts.onResponse;
  }

  async request(input: { path: string; method: string; query?: Record<string, string | number | boolean | undefined>; body?: unknown; headers?: Record<string, string> }): Promise<Response> {
    const url = new URL(this.baseUrl + input.path);
    if (input.query) {
      for (const [k, v] of Object.entries(input.query)) {
        if (v !== undefined) url.searchParams.append(k, String(v));
      }
    }
    const headers: Record<string, string> = { ...this.defaultHeaders, ...(input.headers ?? {}) };
    const searchParams = url.searchParams;
${injectBody}
    const init: RequestInit = { method: input.method, headers };
    if (input.body !== undefined) {
      headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
      init.body = JSON.stringify(input.body);
    }
    let req = new Request(url.toString(), init);
    if (this.onRequest) req = await this.onRequest(req);
    let res = await this.fetchImpl(req);
    if (this.onResponse) res = await this.onResponse(res);
    if (!res.ok) {
      const requestId = res.headers.get("x-request-id");
      let body: unknown = null;
      try { body = await res.clone().json(); } catch { try { body = await res.clone().text(); } catch { /* ignore */ } }
      throwForResponse({ status: res.status, requestId, body, code: null });
    }
    return res;
  }
}
`;
}

function buildAuthUnion(schemes: readonly AuthSchemeDescriptor[]): string {
  if (schemes.length === 0) return 'never & { __skillshipNoAuth: true }';
  const parts = new Set<string>();
  for (const s of schemes) {
    if (s.kind === "bearer") parts.add('{ kind: "bearer"; token: string }');
    if (s.kind === "apiKey") parts.add('{ kind: "apiKey"; value: string; in: "header" | "query"; name: string }');
    if (s.kind === "basic") parts.add('{ kind: "basic"; username: string; password: string }');
  }
  return [...parts].sort().join(" | ");
}

function buildInjectBody(schemes: readonly AuthSchemeDescriptor[]): string {
  if (schemes.length === 0) return "    // no auth schemes projected";
  const lines: string[] = [];
  lines.push('    if (this.auth.kind === "bearer") {');
  lines.push('      Object.assign(headers, { "Authorization": `Bearer ${this.auth.token}` });');
  lines.push('    }');
  if (schemes.some((s) => s.kind === "apiKey")) {
    lines.push('    if (this.auth.kind === "apiKey") {');
    lines.push('      const value = this.auth.value;');
    lines.push('      if (this.auth.in === "header") headers[this.auth.name] = value;');
    lines.push('      else searchParams.append(this.auth.name, value);');
    lines.push('    }');
  }
  if (schemes.some((s) => s.kind === "basic")) {
    lines.push('    if (this.auth.kind === "basic") {');
    lines.push('      const encoded = Buffer.from(`${this.auth.username}:${this.auth.password}`).toString("base64");');
    lines.push('      headers["Authorization"] = `Basic ${encoded}`;');
    lines.push('    }');
  }
  return lines.join("\n");
}

export function runtimePlugin(schemes: readonly AuthSchemeDescriptor[]): unknown {
  return {
    name: "@skillship/sdk-runtime",
    output: "runtime",
    handler: () => generateRuntimeModule(schemes),
  };
}
