// Auto-generated by @skillship/sdk-plugin-mcp-catalog. Do not edit by hand.

export interface CatalogParam {
  readonly name: string;
  readonly in: "path" | "query" | "body";
  readonly type: string;
  readonly required: boolean;
}

export interface CatalogEntry {
  readonly id: string;
  readonly accessor: readonly [string, string];
  readonly httpMethod: string;
  readonly path: string;
  readonly summary: string;
  readonly description: string;
  readonly params: readonly CatalogParam[];
  readonly annotations: {
    readonly destructive: boolean;
    readonly readOnly: boolean;
    readonly idempotent: boolean;
  };
  readonly paginated: boolean;
}

export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "projects_create",
    accessor: ["projects", "create"] as const,
    httpMethod: "POST",
    path: "/projects",
    summary: "Create a project",
    description: "",
    params: [
      {
        name: "body",
        in: "body",
        type: "object",
        required: true,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: false,
      idempotent: false,
    },
    paginated: false,
  },
  {
    id: "projects_list",
    accessor: ["projects", "list"] as const,
    httpMethod: "GET",
    path: "/projects",
    summary: "List projects",
    description: "Returns every project visible to the caller.",
    params: [
      {
        name: "limit",
        in: "query",
        type: "integer",
        required: false,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: true,
      idempotent: true,
    },
    paginated: false,
  },
];
