// Auto-generated by @skillship/sdk-plugin-resource-tree. Do not edit by hand.
import { Client } from "./runtime.js";

export interface ResourceTree {
  readonly projects: {
    list: (opts?: RequestOpts) => Promise<Response>;
    create: (opts?: RequestOpts) => Promise<Response>;
  };
}

interface RequestOpts {
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
  body?: unknown;
  pathParams?: Record<string, string | number>;
}

export function attachResources(client: Client): Client & ResourceTree {
  return Object.assign(client, {
    projects: {
      list: (opts?: RequestOpts) =>
        client.request({
          method: "GET",
          path: "/projects",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
      create: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/projects",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
  });
}
