// Auto-generated by @skillship/sdk-plugin-runtime. Do not edit by hand.
import { throwForResponse, TimeoutError } from "./errors.js";

export type AuthConfig = { kind: "bearer"; token: string };

export interface ClientOptions {
  baseUrl: string;
  auth: AuthConfig;
  defaultHeaders?: Record<string, string>;
  fetch?: typeof fetch;
  timeout?: number;
  onRequest?: (req: Request) => Request | Promise<Request>;
  onResponse?: (res: Response) => Response | Promise<Response>;
}

export class Client {
  readonly baseUrl: string;
  readonly auth: AuthConfig;
  readonly defaultHeaders: Record<string, string>;
  readonly fetchImpl: typeof fetch;
  readonly timeout: number | undefined;
  readonly onRequest:
    | ((req: Request) => Request | Promise<Request>)
    | undefined;
  readonly onResponse:
    | ((res: Response) => Response | Promise<Response>)
    | undefined;

  constructor(opts: ClientOptions) {
    // Normalize baseUrl to end with exactly one trailing slash for safe relative URL resolution.
    this.baseUrl = opts.baseUrl.replace(/\/+$/, "") + "/";
    this.auth = opts.auth;
    this.defaultHeaders = opts.defaultHeaders ?? {};
    this.fetchImpl = opts.fetch ?? globalThis.fetch;
    this.timeout = opts.timeout;
    this.onRequest = opts.onRequest;
    this.onResponse = opts.onResponse;
  }

  async request(input: {
    path: string;
    method: string;
    pathParams?: Record<string, string | number>;
    query?: Record<string, string | number | boolean | undefined>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<Response> {
    // Substitute path parameters (e.g. {id}) with encoded values before URL construction.
    let resolvedPath = input.path;
    if (input.pathParams) {
      for (const [k, v] of Object.entries(input.pathParams)) {
        resolvedPath = resolvedPath.replace(
          `{${k}}`,
          encodeURIComponent(String(v)),
        );
      }
    }
    // Strip a single leading slash from path so URL() resolves it as relative to baseUrl.
    const relPath = resolvedPath.startsWith("/")
      ? resolvedPath.slice(1)
      : resolvedPath;
    const url = new URL(relPath, this.baseUrl);
    if (input.query) {
      for (const [k, v] of Object.entries(input.query)) {
        if (v !== undefined) url.searchParams.append(k, String(v));
      }
    }
    const headers: Record<string, string> = {
      ...this.defaultHeaders,
      ...(input.headers ?? {}),
    };
    const searchParams = url.searchParams;
    if (this.auth.kind === "bearer") {
      headers["Authorization"] = `Bearer ${this.auth.token}`;
    }
    const init: RequestInit = { method: input.method, headers };
    if (input.body !== undefined) {
      headers["Content-Type"] = headers["Content-Type"] ?? "application/json";
      init.body = JSON.stringify(input.body);
    }
    const controller = new AbortController();
    const timeoutId =
      this.timeout !== undefined
        ? setTimeout(() => controller.abort(), this.timeout)
        : null;
    init.signal = controller.signal;
    let req = new Request(url.toString(), init);
    try {
      if (this.onRequest) req = await this.onRequest(req);
      let res = await this.fetchImpl(req);
      if (this.onResponse) res = await this.onResponse(res);
      if (!res.ok) {
        const requestId = res.headers.get("x-request-id");
        let body: unknown = null;
        try {
          body = await res.clone().json();
        } catch {
          try {
            body = await res.clone().text();
          } catch {
            /* ignore */
          }
        }
        throwForResponse({ status: res.status, requestId, body, code: null });
      }
      return res;
    } catch (err) {
      if (controller.signal.aborted) {
        throw new TimeoutError({
          status: 0,
          requestId: null,
          body: null,
          code: "timeout",
          message: `Request timed out after ${this.timeout}ms`,
        });
      }
      throw err;
    } finally {
      if (timeoutId !== null) clearTimeout(timeoutId);
    }
  }
}
