// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import type {
  Op028F4Be7615A5FafData,
  Op028F4Be7615A5FafResponses,
  Op4Ce2F98E1F94162eData,
  Op4Ce2F98E1F94162eErrors,
  Op4Ce2F98E1F94162eResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List projects
 *
 * Returns every project visible to the caller.
 */
export const op4Ce2F98E1F94162E = <ThrowOnError extends boolean = false>(
  options: Options<Op4Ce2F98E1F94162eData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    Op4Ce2F98E1F94162eResponses,
    Op4Ce2F98E1F94162eErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects",
    ...options,
  });

/**
 * Create a project
 */
export const op028F4Be7615A5Faf = <ThrowOnError extends boolean = false>(
  options: Options<Op028F4Be7615A5FafData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    Op028F4Be7615A5FafResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
