// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type ProjectInput = {
  [key: string]: unknown;
};

export type ProjectList = {
  [key: string]: unknown;
};

export type Op4Ce2F98E1F94162eData = {
  body?: never;
  headers: {
    "X-Trace-Id": string;
  };
  path?: never;
  query?: {
    limit?: number;
  };
  url: "/projects";
};

export type Op4Ce2F98E1F94162eErrors = {
  /**
   * 401
   */
  401: {
    [key: string]: unknown;
  };
};

export type Op4Ce2F98E1F94162eError =
  Op4Ce2F98E1F94162eErrors[keyof Op4Ce2F98E1F94162eErrors];

export type Op4Ce2F98E1F94162eResponses = {
  /**
   * 200
   */
  200: ProjectList;
};

export type Op4Ce2F98E1F94162eResponse =
  Op4Ce2F98E1F94162eResponses[keyof Op4Ce2F98E1F94162eResponses];

export type Op028F4Be7615A5FafData = {
  body: ProjectInput;
  path?: never;
  query?: never;
  url: "/projects";
};

export type Op028F4Be7615A5FafResponses = {
  /**
   * 201
   */
  201: {
    [key: string]: unknown;
  };
};

export type Op028F4Be7615A5FafResponse =
  Op028F4Be7615A5FafResponses[keyof Op028F4Be7615A5FafResponses];
