# {{PACKAGE_NAME}}

Auto-generated TypeScript SDK for {{PRODUCT_NAME}}.

## Install

```sh
npm install {{PACKAGE_NAME}}
```

## Authentication

Set the following environment variables before constructing the client:

{{README_ENV_TABLE}}

{{README_AUTH_QUICKSTART}}

{{README_TOKEN_PROVIDER}}

{{README_RETRIES}}

{{README_PAGINATION}}

Generated by [skillship](https://github.com/firmislabs/skillship).
