# {{PACKAGE_NAME}}

Auto-generated TypeScript SDK for {{PRODUCT_NAME}}.

## Install

```sh
npm install {{PACKAGE_NAME}}
```

## Usage

```ts
import { Client, attachResources } from "{{PACKAGE_NAME}}";

const client = attachResources(
  new Client({
    baseUrl: "https://api.{{PRODUCT_NAME}}",
    auth: { kind: "bearer", token: process.env.API_TOKEN! },
  }),
);
```

Generated by [skillship](https://github.com/firmislabs/skillship).
