// Auto-generated by @skillship/sdk-plugin-auth. Do not edit by hand.
import { AuthError, ConfigError } from "./errors.js";

// Narrow ambient so resolveAuthFromEnv compiles without @types/node — the
// emitted package ships zero dependencies and a DOM-only lib. At runtime this is
// the real Node `process`; in non-Node hosts env simply resolves to undefined.
declare const process: { env: Record<string, string | undefined> };
export type AuthConfig =
  | { kind: "bearer"; token: string }
  | { kind: "tokenProvider"; getToken: () => Promise<string> };

export function resolveAuthFromEnv(): AuthConfig | null {
  const env = process.env;
  if (env.GQL_EXAMPLE_TOKEN) {
    return { kind: "bearer", token: env.GQL_EXAMPLE_TOKEN };
  }
  return null;
}

export const REQUIRED_ENV_VARS: readonly string[] = ["GQL_EXAMPLE_TOKEN"];

export class AuthManager {
  private readonly auth: AuthConfig;
  private readonly fetchImpl: typeof fetch;

  constructor(auth: AuthConfig, fetchImpl: typeof fetch) {
    this.auth = auth;
    this.fetchImpl = fetchImpl;
  }

  async applyAuth(
    headers: Record<string, string>,
    searchParams: URLSearchParams,
  ): Promise<void> {
    const auth = this.auth;
    if (auth.kind === "bearer") {
      headers["Authorization"] = `Bearer ${auth.token}`;
      return;
    }
    if (auth.kind === "tokenProvider") {
      const token = await auth.getToken();
      headers["Authorization"] = `Bearer ${token}`;
    }
  }

  onUnauthorized(): boolean {
    if (this.auth.kind === "tokenProvider") {
      return true;
    }
    return false;
  }
}
