// Auto-generated by @skillship/sdk-plugin-errors. Do not edit by hand.

export class APIError extends Error {
  readonly status: number;
  readonly requestId: string | null;
  readonly body: unknown;
  readonly code: string | null;
  constructor(args: {
    status: number;
    requestId: string | null;
    body: unknown;
    code: string | null;
    message: string;
  }) {
    super(args.message);
    this.name = "APIError";
    this.status = args.status;
    this.requestId = args.requestId;
    this.body = args.body;
    this.code = args.code;
  }
}

export class BadRequestError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "BadRequestError";
  }
}
export class UnauthorizedError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "UnauthorizedError";
  }
}
export class ForbiddenError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "ForbiddenError";
  }
}
export class NotFoundError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "NotFoundError";
  }
}
export class RateLimitError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "RateLimitError";
  }
}
export class InternalServerError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "InternalServerError";
  }
}
export class TimeoutError extends APIError {
  constructor(a: ConstructorParameters<typeof APIError>[0]) {
    super(a);
    this.name = "TimeoutError";
  }
}

// Client-side errors raised before/around a request (no HTTP response involved).
// auth.ts constructs these with a plain message: `new AuthError("...")`.
export class AuthError extends APIError {
  constructor(message: string) {
    super({
      status: 0,
      requestId: null,
      body: null,
      code: "auth_error",
      message,
    });
    this.name = "AuthError";
  }
}
export class ConfigError extends APIError {
  constructor(message: string) {
    super({
      status: 0,
      requestId: null,
      body: null,
      code: "config_error",
      message,
    });
    this.name = "ConfigError";
  }
}

export function throwForResponse(args: {
  status: number;
  requestId: string | null;
  body: unknown;
  code: string | null;
  suffix?: string;
}): never {
  const message = "API error " + String(args.status) + (args.suffix ?? "");
  switch (args.status) {
    case 400:
      throw new BadRequestError({ ...args, message });
    case 401:
      throw new UnauthorizedError({ ...args, message });
    case 403:
      throw new ForbiddenError({ ...args, message });
    case 404:
      throw new NotFoundError({ ...args, message });
    case 429:
      throw new RateLimitError({ ...args, message });
    default:
      if (args.status >= 500 && args.status <= 599)
        throw new InternalServerError({ ...args, message });
      throw new APIError({ ...args, message });
  }
}
