// Auto-generated by @skillship/sdk-plugin-mcp-catalog. Do not edit by hand.

export interface CatalogParam {
  readonly name: string;
  readonly in: "path" | "query" | "body";
  readonly type: string;
  readonly required: boolean;
}

export interface CatalogEntry {
  readonly id: string;
  readonly accessor: readonly [string, string];
  readonly httpMethod: string;
  readonly path: string;
  readonly summary: string;
  readonly description: string;
  readonly params: readonly CatalogParam[];
  readonly annotations: {
    readonly destructive: boolean;
    readonly readOnly: boolean;
    readonly idempotent: boolean;
  };
  readonly paginated: boolean;
}

export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "mutation_create_project",
    accessor: ["mutation", "createProject"] as const,
    httpMethod: "POST",
    path: "/graphql#createProject",
    summary: "Create a project",
    description: "",
    params: [
      {
        name: "input",
        in: "query",
        type: "string",
        required: false,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: false,
      idempotent: false,
    },
    paginated: false,
  },
  {
    id: "query_projects",
    accessor: ["query", "projects"] as const,
    httpMethod: "POST",
    path: "/graphql#projects",
    summary: "List all projects",
    description: "",
    params: [
      {
        name: "limit",
        in: "query",
        type: "string",
        required: false,
      },
    ],
    annotations: {
      destructive: false,
      readOnly: false,
      idempotent: false,
    },
    paginated: false,
  },
];
