// Auto-generated by @skillship/sdk-plugin-resource-tree. Do not edit by hand.
import { Client } from "./runtime.js";

export interface ResourceTree {
  readonly mutation: {
    createProject: (opts?: RequestOpts) => Promise<Response>;
  };
  readonly query: { projects: (opts?: RequestOpts) => Promise<Response> };
}

interface RequestOpts {
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
  body?: unknown;
  pathParams?: Record<string, string | number>;
}

export function attachResources(client: Client): Client & ResourceTree {
  return Object.assign(client, {
    mutation: {
      createProject: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/graphql#createProject",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
    query: {
      projects: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/graphql#projects",
          pathParams: opts?.pathParams,
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
  });
}
