// Auto-generated by @skillship/sdk-plugin-resource-tree. Do not edit by hand.
import { Client } from "./runtime.js";

export interface ResourceTree {
  readonly mutation: {
    op_a407a3944801e8fb: (opts?: RequestOpts) => Promise<Response>;
  };
  readonly query: {
    op_d3c34b8f2769d5ff: (opts?: RequestOpts) => Promise<Response>;
  };
}

interface RequestOpts {
  query?: Record<string, string | number | boolean | undefined>;
  headers?: Record<string, string>;
  body?: unknown;
}

export function attachResources(client: Client): Client & ResourceTree {
  return Object.assign(client, {
    mutation: {
      op_a407a3944801e8fb: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/graphql#createProject",
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
    query: {
      op_d3c34b8f2769d5ff: (opts?: RequestOpts) =>
        client.request({
          method: "POST",
          path: "/graphql#projects",
          query: opts?.query,
          headers: opts?.headers,
          body: opts?.body,
        }),
    },
  });
}
