// This file is auto-generated by @hey-api/openapi-ts

import { client } from "./client.gen.js";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "./client/index.js";
import type {
  OpA407A3944801E8FbData,
  OpA407A3944801E8FbResponses,
  OpD3C34B8F2769D5FfData,
  OpD3C34B8F2769D5FfResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Create a project
 */
export const opA407A3944801E8Fb = <ThrowOnError extends boolean = false>(
  options?: Options<OpA407A3944801E8FbData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    OpA407A3944801E8FbResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/graphql#createProject",
    ...options,
  });

/**
 * List all projects
 */
export const opD3C34B8F2769D5Ff = <ThrowOnError extends boolean = false>(
  options?: Options<OpD3C34B8F2769D5FfData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    OpD3C34B8F2769D5FfResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/graphql#projects",
    ...options,
  });
