// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type OpA407A3944801E8FbData = {
  body?: never;
  path?: never;
  query?: {
    input?: string;
  };
  url: "/graphql#createProject";
};

export type OpA407A3944801E8FbResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type OpD3C34B8F2769D5FfData = {
  body?: never;
  path?: never;
  query?: {
    limit?: string;
  };
  url: "/graphql#projects";
};

export type OpD3C34B8F2769D5FfResponses = {
  /**
   * OK
   */
  200: unknown;
};
